lib/Mojo/Server/Prefork.pm

Since setuidgid now may croak, we need to set cleanup(0) before calling setuidgid

Prevent possibility of deleting pid file by child

---

lib/Mojo/Util.pm
t/mojo/util.t

For example, given an HTTP response containing:
Set-Cookie: a=b; expires=Wednesday, 17-Feb-2016 23:59:59 GMT;
Set-Cookie: c=d; expires=Wednesday, 17-Feb-2016 23:59:59 GMT;
Mojo::Message::Response::cookies in 5.77 returns both cookies but 5.79 only returns the first one.

Fix regression - some web frameworks terminate cookies with semicolons

---

lib/Mojolicious/Command/test.pm

See also [this](https://github.com/Perl-Toolchain-Gang/Test-Harness/commit/18794a8565633ae08f048b9cf6c25b03be6e1020) and [this](https://rt.cpan.org/Public/Bug/Display.html?id=58229) discussions

Test::Harness enables global warnings by default. Disable this behavior

---

lib/Mojo/Parameters.pm

$params->param() is removed and I sould use $params->names instead. right?

Removed old api usage from document

---

lib/Mojo/Transaction/WebSocket.pm

Mojo::Transaction (and child classes) lost support for custom sockets in 1712764315fbee14c9a1d03de48833ed064191a5.

POD: no custom socket support here either.

---

lib/Mojo/Util.pm
t/mojo/util.t

Usefull with Mojo::Pg::Results::text and null values.

Removed warning when using undef values in tablify

---

lib/Mojo/Cookie.pm

Self-explanatory - broken links in POD to non-existent classes.
thanks,
Michael

fix POD links to Mojo::Cookie::* classes

---

lib/Mojo/JSON.pm

Fixes _decode_value() to use the true and false functions in case they have been monkey patched to return different boolean objects, e.g. by Mojo::JSON::MaybeXS.

use true/false functions instead of variables to allow monkey-patched Mojo::JSON

---

lib/Test/Mojo.pm
t/mojolicious/validation_lite_app.t

This allows for testing for whether the page contains the expected number of elements, based on the provided selector. You can either test for the exact number, or more/less than the specified number.

Added element_count_is method

---

lib/Mojolicious/Plugin/PODRenderer.pm
t/mojolicious/pod_renderer_lite_app.t

For now Mojolicious removes this spaces only when it renders /perldoc. Will be good if `pod_to_html` helper will also remove this useless whitespaces.
See also https://rt.cpan.org/Public/Bug/Display.html?id=103389

pod_to_html helper now will remove spaces at the start of the line for code blocks

---

lib/Mojolicious/Types.pm
t/mojo/cgi.t
t/mojo/psgi.t
t/mojolicious/charset_lite_app.t
t/mojolicious/group_lite_app.t
t/mojolicious/lite_app.t
t/mojolicious/restful_lite_app.t
t/mojolicious/types.t

IE 7,8,9 has bug with decoding of json response without encoding.
See http://stackoverflow.com/questions/8481453/jquery-ajax-request-doesnt-success-with-json-on-ie
The default encoding of application/json is UTF-8.
http://www.ietf.org/rfc/rfc4627.txt
That means, we can specify encoding in response without any trouble.

Fix IE bug with decoding json response without encoding.

---

lib/Mojo/Base.pm
lib/Mojo/DOM.pm
lib/Mojo/IOLoop/Stream.pm
lib/Mojo/URL.pm
lib/Mojolicious/Plugins.pm
lib/Test/Mojo.pm

I feel silly submitting this, but it's been nagging me in the brain, ever since `sri` mentioned it: http://irclog.perlgeek.de/mojo/search/?nick=sri&q=%22would+be+right%22
I've used a script to find unsorted methods and here's its output, to more easily see what was moved around. The lines starting with a `#` indicate blocks that contain unsorted methods:
```
/var/www/tmp/mojo/lib/Test/Mojo.pm has unsorted methods:
==Original=== | ===Sorted===
app | app
content_is | content_is
content_isnt | content_isnt
content_like | content_like
delete_ok | delete_ok
element_count_is | element_count_is
element_exists | element_exists
element_exists_not | element_exists_not
finish_ok | finish_ok
finished_ok | finished_ok
get_ok | get_ok
head_ok | head_ok
header_is | header_is
header_isnt | header_isnt …
```

Sort method names alphabetically in the code/documentation

---

lib/Mojo/Collection.pm
t/mojo/collection.t

Adds Mojo::Collection::TO_JSON
The name is slightly misleading as it doesn't convert to JSON, rather it returns an array reference in the same way as to_array. This lets Mojo::JSON and friends convert a Mojo::Collection to a JSON array.
Amongst other things it reduces noise when returning Mojo::Pg result sets as JSON:
$c->render(json => {foo => $results->hashes});
vs
$c->render(json => {foo => $results->hashes->to_array});

TO_JSON for Mojo::Collection

---

Makefile.PL

`dynamic_config` should really be disabled so that CPAN tools know that Mojolicious has static prerequisities (as per https://metacpan.org/pod/CPAN::Meta::Spec#dynamic_config). To do this, the `META_MERGE` contents are updated to follow v2 of the META spec. The diff of the resulting META.json with the current META.json is linked below.
https://gist.github.com/Grinnz/ca3f85988463e34b8118

update Makefile.PL to meta-spec v2 and set dynamic_config to 0

---

lib/Mojo/Collection.pm
t/mojo/collection.t

This change adds a callback to the uniq method in Mojo::Collection, allowing users to define what constitutes a unique element. This permits collections of hashes and arrays to be de-duplicated, rather than just elements which stringify reasonably (strings, numbers, overloaded objects).

add callback to uniq method of collection

---

lib/Mojolicious/resources/templates/mojo/menubar.html.ep

This fixes the JS error when clicking on PODRenderer rendered table of contents, when links contain special characters. Relevant IRC Conversation: http://irclog.perlgeek.de/mojo/2015-11-03#i_11475962
Tested on:
* Palemoon 24.6.2
* IE10, Windows 7
* IE11, Windows 8.1
* Firefox 43
* Chrome 47 Dev
* Opera 32
* Safari 9, OSX EL Capitan
* Safari 5.1, Windows 10

Fix JavaScript errors when links in TOC have special characters

---

lib/Mojolicious/Guides/Cookbook.pod

Apache mod_proxy and mod_proxy_wstunnel supports proxying WebSockets, so this adds a configuration example to the Cookbook.

Cookbook: Add WebSocket configuration to Apache example.

---

lib/Mojolicious/Plugin/TagHelpers.pm

at the line: 
[TagHelpers.pm#L25](https://github.com/kraih/mojo/blob/master/lib/Mojolicious/Plugin/TagHelpers.pm#L25)
`sub { _input(shift, shift, value => shift, @_, type => 'checkbox') });`
The expression:
`value => shift, @_`
duplicated at:
[TagHelpers.pm#L68](https://github.com/kraih/mojo/blob/master/lib/Mojolicious/Plugin/TagHelpers.pm#L68)
`my %attrs = @_ % 2 ? (value => shift, @_) : @_;`
So we can just write:
`sub { _input(shift, shift, @_, type => 'checkbox') });`
or even better:
`sub { _input(@_, type => 'checkbox') });`

Small optimizations

---

Changes
lib/Mojo/Server/Morbo.pm
t/mojo/morbo.t

Squashed commit of the following:
commit a210794ca2b27848fb03857be131b4a24b771899
Author: Lee Johnson <lee@givengain.ch>
Date:   Tue Mar 8 09:28:24 2016 +0100
add ->modified_files, deprecate ->check
in Mojo::Server::Morbo - allows retrieval of entire list of files
changed (or undef) preventing morbo getting into a restart loop if
many files have changed. ->check is now redundant so deprecated
update tests in t/mojo/morbo.t tp reflect above changes
commit 3345a9d48e9f43d1111ae7e20b589ec1a9fd6d2c
Author: Andrew Nugged <nugged@gmail.com>
Date:   Mon Mar 7 23:00:19 2016 +0200
Handle multiple changed files at once for restart
If you change numerous files at once or one-by-one in second(s),
Morbo saw first file changed and tried to restart right away
(though meanwhile restart process started, …

add ->modified_files, deprecate ->check

---

t/mojo/hypnotoad.t

Found two tests that had inverted names, as if there was a copy and paste and later the test was inverted or something.

Fix two test names to match the test result

---

lib/Mojo/UserAgent/CookieJar.pm
t/mojo/cookiejar.t

They say set-cookie with Max-Age=0 means it expires immidiately but current Mojo::UserAgent doesn't handle it that way.
I found it in real world use case. PHP applications sometimes send cookies as follows for session renewal or something.
HTTP/1.1 302 Found
Content-Type: text/html; charset=UTF-8
Server: nginx
X-Powered-By: PHP/5.6.16
Vary: Accept-Encoding
Date: Sun, 12 Jun 2016 13:33:55 GMT
Set-Cookie: PHPSESSIDADMIN=deleted; expires=Thu, 01-Jan-1970 00:00:01 GMT; Max-Age=0; path=/
Set-Cookie: PHPSESSIDADMIN=qkm88lcmdt1bmls1ngb3e57ci3; expires=Sun, 12-Jun-2016 19:33:54 GMT; Max-Age=21600; path=/admin; HttpOnly
Location: http://example.com/admin/
Recieving the response the ua unexpectedly sends back the Max-Age=0 cookie again within the same second in favor of redirection.
I checked …

fixed a bug where max-age=0 cookies would not expires until next second

---

Changes
lib/Mojolicious/Command/get.pm

As reported by me on irc (http://irclog.perlgeek.de/mojo/2016-06-25#i_12734495) the get command ignores `-H` options passed to it for which the header is given no value (ie `-H X-Bender:`). The header is not built into the request at all. This patch adds that behavior
Interesting to note that curl has this same problem and due to their api they cannot fix it (though it seems that the author would choose to if possible). See the email here https://curl.haxx.se/mail/lib-2010-08/0174.html . As we can fix it I vote that we should.

fix zero length header value bug in Mojolicious::Command::get

---

lib/Mojo/DOM/CSS.pm
t/mojo/dom.t

Given a tag with a defined but value-less attribute like
``` html
<input type="text" name="example" value>
```
(for example generated using the taghelper plugin with ```$c->text_field('example', value => undef)```),
the CSS selector
``` CSS
input[value="myname"]
```
will match regardless of the non-fitting value.
I tested the behaviour in Firefox and assume the selector should not match.
I added a test and a patch (although I doubt the patch is optimal).
Thank you!

Attribute Selector fails for defined attributes with wrong values in Mojo::DOM::CSS

---

examples/connect-proxy.pl
t/mojo/daemon_ipv6_tls.t
t/mojo/websocket_proxy.t
t/mojo/websocket_proxy_tls.t

Fix an issue in the testsuite (t/mojo/websocket_proxy.t): the `$server` variable contains either an object or `undef`. Using `defined` instead of `length` is the right thing (whatever perl version).
The original code provokes a warning when running the testsuite on perl 5.10.1.

websocket_proxy.t: fix warning on perl 5.10.1

---

lib/Mojo/UserAgent/Transactor.pm
t/mojo/transactor.t

As detailed in #999, 303 redirects should be handled with a `GET` method. This PR implements that behavior.

handle all 303 redirects with a GET method

---

lib/Mojolicious/Routes/Route.pm

Corrects a simple typo
The typo was noticed whilst packaging version 7.07 for Debian

Fix a typo

---

Changes
lib/Mojolicious.pm
t/mojolicious/app.t

Move the log initialization from the `new` constructor to the attribute default.
The current behavior is a good "sane default" but is difficult to override when desired. By encapsulating the default logic into an overloadable attribute definition a subclass application can easily change the default initialization. This also has the added benefits of making documentation of these default initialization behaviors easier and makes setting the mode attribute in the startup method more useful.
IRC discussion starts here: https://irclog.perlgeek.de/mojo/2016-11-28#i_13642669

move default log behavior to overloaded attribute

---

lib/Mojo/Server/Morbo.pm
t/mojo/morbo.t

Currently, if broken symlinks exist in the directories watched by morbo, `stat` will return undefined values for that file causing unnecessary caching and warnings. Anything which does not return defined values can simply be skipped by morbo.
Reduce computation and avoid warnings if watched directories have broken symlinks.
https://irclog.perlgeek.de/mojo/2016-12-27#i_13808575

prevent warnings whenever morbo checks broken symlinks

---

lib/Mojo/Transaction.pm

A typo detected whilst packaging 7.13 for Debian

Correct typo in POD (lintian)

---

lib/Mojo/IOLoop/Subprocess.pm
t/mojo/subprocess.t

Exit early when the subprocess parent callback is in the wrong process
Closes #1054, see also:
* http://irclog.perlgeek.de/mojo/2016-08-26#i_13096567
- http://irclog.perlgeek.de/mojo/2014-07-23#i_9067566
- https://gist.github.com/oe​tiker/bbd3e468b0d25815738c
* http://irclog.perlgeek.de/mojo/2016-08-27#i_13101743
Note that I have adapted the example from the bug report as a test. I'd like to see that tested on a few platforms before merging.

Proposed fix for #1054

---

lib/Mojolicious.pm

Document that around_action can be called more than once for the current request.
Because this is perhaps surprising.
https://irclog.perlgeek.de/mojo/2017-02-16#i_14111623

document that around_action can be called more than once

---

lib/Mojo/Loader.pm

Update document for Mojo::Loader::load_class function, because the return value is mismatch with the source code
I am reading the Mojo source code to learn such elegant framework, and find this document mismatch with code, would like to update it if my understanding is correct

update document for load_class function

---

lib/Mojolicious/Command/generate/app.pm
t/mojolicious/commands.t

Generate the config file and enable the config plugin with the mojo generate app command in the full blown Mojo app.
I think that the vast majority of web apps end up needing the config mechanism. So, instead of having the developers looking throughout the docs how to enable the plugin, how to name the config file, how to access the config variables within the app, provide it to them automatically at create time.
All the rejection reasons of the previous PRs, plus the discussions on IRC

The config mechanism in the app generated with generate app command

---

README.md

Fix url that contained a trailing '>' character which causes the mojolicious.org site to return a 404 not found error.
Simple fix to prevent a 404 not found error.

Fixed broken documentation url

---

lib/Mojo/Date.pm
t/mojo/date.t

Fixes Mojo::Date when used with negative numbers as epoch
I found the issue when representing birth dates with Mango::Time objects - a date before the epoch like 1965-12-21 would emit uninit warnings and end up represented as Jan 1, 1970. This comes from https://github.com/oliwer/mango/blob/master/lib/Mango/BSON/Time.pm#L12 which in turn points to Mojo::Date code https://github.com/kraih/mojo/blob/master/lib/Mojo/Date.pm#L25 
For example, running the test included in this PR with the code in master gives the output
```
$ prove -I lib t/mojo/date.t
t/mojo/date.t .. 1/? Use of uninitialized value in gmtime at /Users/ferreira/ws/mojo/lib/Mojo/Date.pm line 66.
t/mojo/date.t .. Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/40 subtests 
Test Summary Report
------------------- …
```

Mojo::Date: epoch can be a negative number

---

lib/Mojo/Server/Morbo.pm
lib/Mojo/Server/Morbo/Backend.pm
lib/Mojo/Server/Morbo/Backend/Poll.pm
script/morbo
t/mojo/file.t
t/mojo/lib/Mojo/Server/Morbo/Backend/TestBackend.pm
t/mojo/morbo.t
t/pod_coverage.t

Reloader class can be set on the command line or as an ENV. Move current implementation to default backend ::Poll.
This change makes it possible to write OS specific file watchers for morbo that is more performant than the default poll implementation. To confirm that the implementation works, I've made a simple Inotify watcher here: https://gist.github.com/anonymous/60d22a13a103796a22662782b2dcb436
This pull request is a proposal to resolve #1071

Add support for pluggable reloader backends in Morbo. 

---

lib/Mojo/WebSocket.pm

These changes slightly improve the speed of parsing Websocket frames by removing the substr() calls and skipping bytes as needed instead. Considering only the unpack/substr calls, these changes give ~20% speed improvement in benchmarks.
The "Extended payload (64-bit with 32-bit fallback)" unpack format is slightly more verbose than required in the 32-bit fallback ("x2x4" vs "x6") but I believe this expanded form makes its behaviour easier to follow and did not appear to be detrimental to performance.
Optimisation.
No references. Optimisation potential was noticed while studying the code.

Optimise frame parsing by removing substr calls

---

lib/Mojo/File.pm
t/mojo/file.t

I'm not sure why it works on absolute paths but I suspect it has something to do with the stringification of the scalar reference. That said, if that works for absolute paths I can't think of why it doesn't work for relative ones. Anyway, this fix seems fairly self-evident and the text works.

fix basename on a relative path

---

lib/Mojolicious/Static.pm
t/mojolicious/production_app.t

…to permit examining, overriding, or disabling any or all bundled files. May resolve #1094
Enumerate bundled, static files so application can examine or modify their resolution at runtime. For example, a Mojolicious::Lite app could:
delete app->static->special->{'favicon.ico'};
and then proceed to serve `favicon.ico` from a route.  
app->static->special->{'mojo/jquery/jquery.js'} =
app->home->child('resources', 'jquery.js');
would override the built-in jQuery for error pages with one in the app's `resources` directory.
Note: It might also be desirable to permit values which are Mojo::Asset objects, rather than filenames.
[issue #1094 ](https://github.com/kraih/mojo/issues/1094)

Add 'special' attribute to Mojolicious::Static

---

lib/Mojo/Base.pm
lib/Mojolicious/Command/version.pm
t/mojo/roles.t

Add with_roles method to Mojo::Base, per the specs described here:
https://irclog.perlgeek.de/mojo/2017-08-08#i_14984146
Allow multiple developers to extend key Mojolicious classes (Test::Mojo, Mojo::UserAgent, etc)
using Role::Tiny (optional dependency)
https://irclog.perlgeek.de/mojo/2017-08-08#i_14984146

Mojo::Base::with_roles patch

---

lib/Mojo/IOLoop/TLS.pm

since IO::Socket::SSL >= 1.965 `\undef` means no CA, that is specificed as `''` in older versions
Otherwise we observe errors like:
> Mojo::Reactor::Poll: I/O watcher failed: SSL_ca_file SCALAR(0x2490188) does not exist at /usr/lib/perl5/vendor_perl/5.18.2/IO/Socket/SSL.pm line 1616.
https://progress.opensuse.org/issues/23934#change-62720

fix SSL_ca_file reference to undef

---

t/mojolicious/ojo_signatures.t

Without this, I get a test failure because it’s trying to ask a proxy
for localhost, which of course comes back with the wrong content.

ojo_signatures.t: Suppress proxies

---

lib/Mojo/Util.pm
t/mojo/util.t

This change allows tablify to work on non-rectangular arrays without generating errors. For example, when outputting parsed CSV files with trailing empty cells omitted/removed by trimmed whitespace.
Removes the need for looping over and modifying the input array reference several times to prepare it for tablify by the user.
This implements the line-count-even implementation suggested by sri and tests provided by lindleyw in https://github.com/kraih/mojo/pull/1132.

allow tablify to format non-rectangular arrays

---

lib/Mojo/IOLoop/Client.pm
lib/Mojo/IOLoop/TLS.pm
t/mojo/reactor_ev.t

String eval is unnecessary for this type of check. We can consistently use block eval here.
Consistency and avoidance of string eval where it's not needed.

use block eval instead of string eval to load optional modules

---

lib/Mojo/Base.pm

With circular require issues solved, class_to_path can be reused in Mojo::Base for loading modules.
Code reuse

use class_to_path to load modules in Mojo::Base

---

lib/Mojo/IOLoop/Delay.pm

Fix a typo in Mojo::IOLoop::Delay documentation
Correctness

Fix doc typo on Mojo::IOLoop::Delay

---

lib/Mojolicious/Static.pm
t/mojolicious/static_lite_app.t

Data sections in files with `use utf8` active will be decoded to characters when retrieved. It is expected that `use utf8` will be active in Mojolicious source code. Thus static files retrieved from these data sections need to be encoded back to UTF-8 to be served correctly.
https://irclog.perlgeek.de/mojo/2017-12-22#i_15612756

Encode static files from data sections to UTF-8

---

lib/Mojo/JSON.pm

Values that start as numbers won't get the utf8 flag enabled implicitly
through other operations, so it is a good signal that we should encode
as a string.  Additionally, this avoids planned future perl warnings
about performing bitwise operations on strings containing wide
characters.
Discussion regarding deprecation warning:
https://www.nntp.perl.org/group/perl.perl5.porters/2017/12/msg248248.html

JSON encode utf8 flagged scalars as strings

---

lib/Mojolicious/Guides/Cookbook.pod

Add a section about Reverse Proxies, to explain what they are, why you should care about them and how to solve the problem they introduce.
- Information about reverse proxies and how to set them up is a bit scattered around and not always immediately evident in some deployment use cases.
- Looking for `mojolicious reverse proxy` in Google returns solutions that are unnecessary/overkill in the general case (which only involves some configuration).
- [Start of discussion in IRC](https://irclog.perlgeek.de/mojo/2018-01-30#i_15758733)
- [Suggestion to start a PR](https://irclog.perlgeek.de/mojo/2018-02-01#i_15766494)

Add section on Reverse Proxy in Cookbook/CONCEPTS

---

lib/Mojo/IOLoop.pm

Add documentation to Mojo::IOLoop about ->client and ->server making Mojo::IOLoop::Stream objects.

Mojo::IOLoop: Document that ->client and ->server make Mojo::IOLoop::Stream objects

---

lib/Mojo/Exception.pm
t/mojo/exception.t
t/mojo/exception/non_utf8.txt
t/mojo/exception/utf8.txt

Assume source code is bytes if it does not cleanly decode from UTF-8.
A source file may have non-UTF8 data and this causes issues when Mojo::Exception attempts to retrieve context for the exception.
Fixes #1200

fix exceptions triggered from non-UTF-8 files

---

lib/Mojolicious/Validator.pm
t/mojolicious/validation_lite_app.t

make max value optional in num validation check
`num(1)` looks better than `num(1, 999)` or `num(1, 'inf')`

make max optional in num validation check

---

lib/Mojo/DOM/CSS.pm

This causes warnings on 5.10.
Clean up warnings
https://irclog.perlgeek.de/mojo/2018-05-02#i_16119092

Remove ambiguity in use of shift

---

lib/Mojolicious/Static.pm
t/mojolicious/app.t
t/mojolicious/production_app.t
t/mojolicious/testing_app.t

GET requests with embedded backslashes can be used to access local files on Windows hosts
Path separator used in Windows systems is the backslash.
Using backslashes in the path part of a URL can be used on those systems to bypass Mojolicious protection against directory traversal.
To avoid that, this PR blocks any url with backlashes inside the path part of it. 
https://irclog.perlgeek.de/mojo/2018-04-23#i_16083074 and following.

added static files traversal tests and squashed

---

lib/Mojolicious/resources/templates/mojo/exception.html.ep
lib/Mojolicious/resources/templates/mojo/not_found.html.ep

I fixed exception and not_found templates by putting `style` tag inside `head`.
They were not HTML valid (the `style` tag was outside `head` and `body`)

Fix exception and not_found templates HTML validity

---

lib/Mojo/DOM.pm

Wrap cloned dom tree in a root node if it doesn't have one
Keep efficiency of cloning dom trees when not at the root node
#1224 https://irclog.perlgeek.de/mojo/2018-05-18#i_16178465

clone and wrap trees without a root node in _parse

---

lib/Mojo/IOLoop.pm
lib/Mojo/IOLoop/Stream/HTTPClient.pm
lib/Mojo/IOLoop/Stream/HTTPServer.pm
lib/Mojo/IOLoop/Stream/WebSocketClient.pm
lib/Mojo/IOLoop/Stream/WebSocketServer.pm
lib/Mojo/Server/Daemon.pm
lib/Mojo/Server/Prefork.pm
lib/Mojo/UserAgent.pm
t/mojo/ioloop.t
t/mojo/streams.t
t/mojo/user_agent_online.t

Implementing Mojo::IOLoop::Stream subclasses for HTTP and WebSocket connections.
An attempt to implement feature required for an issue.
https://github.com/kraih/mojo/issues/423#issuecomment-376509948

Protocol specific IOLoop streams

---

lib/Mojolicious/Guides.pod

Spelling out the already established variable naming conventions in example documentation in brief
Same as #1237
* #1237
* #1236

Describe variable naming convention in doc examples

---

Makefile.PL
README.md
lib/Mojo/UserAgent.pm
lib/Mojolicious.pm
lib/Mojolicious/Guides.pod
lib/Mojolicious/Guides/Contributing.pod
lib/Mojolicious/Guides/Cookbook.pod
lib/Mojolicious/Guides/FAQ.pod
lib/Mojolicious/Guides/Growing.pod
lib/Mojolicious/Guides/Rendering.pod
lib/Mojolicious/Guides/Routing.pod
lib/Mojolicious/Guides/Testing.pod
lib/Mojolicious/Guides/Tutorial.pod
lib/Mojolicious/resources/templates/mojo/menubar.html.ep

Even tho links are still working via redirect it's nicer to use the new ones.
Note that I did not update appveyor as it seems it didn't automatically follow
the redirect like travis did. Also it seems to be showing the status of
feature branches in our README, which probably isn't a good thing?

Update links to use the new github organization urls.

---

lib/Mojo/Transaction/WebSocket.pm
t/mojo/websocket_frames.t

Detect pmc bit for fragmented compressed messages correctly
Now Mojolicious detects it incorrectly
https://github.com/mojolicious/mojo/issues/1259

detect pmc bit for fragmented messages

---

lib/Mojolicious/Plugin/TagHelpers.pm
t/mojolicious/tag_helper_lite_app.t

passing an undefined start value to select_field TagHelper throws an "uninitialized value" warning
> Use of uninitialized value in list assignment at .../site_perl/5.28.0/Mojolicious/Plugin/TagHelpers.pm line 137.
consistency with other TagHelpers which do not produce a warning when passing undefined start values
Test script:
```
use Mojolicious::Lite;
get '/' => sub {
my $c = shift;
$c->param(txt => undef);
$c->param(cb  => undef);
$c->param(sel => undef);
} => 'index';
app->start;
__DATA__
@@ index.html.ep
%= text_field 'txt'
%= check_box 'cb'
%= select_field 'sel' => [qw(foo bar)]
```

avoid "uninitialized value" warning in select_field

---

lib/Mojo/DynamicMethods.pm

Doing this (ala Class::Method::Modifiers) lets me avoid C3 mro trickery to avoid unexpected linearisation errors - means e.g,. people doing
use Mojo::Base 'Mojolicious::Controller';
twice won't get an error they don't understand. Note that while the example I gave is something that was wrong but accidentally works, it seems to me too easy to get the same helper using class in isa twice and this makes that situation much more predictable

switch DynamicMethods to a pre-cached super

---

lib/Mojo/IOLoop/Subprocess.pm
t/mojo/subprocess.t

Added 'progress' method and event to Mojo::IOLoop::Subprocess, in accordance to kraih's specifications. Includes test, but no documentation just yet.
This pull-request comes after an issue for its implementation was written in the mojo project
issue #1285

added progress notifications to Mojo::IOLoop::Subprocess

---

lib/Mojo/DynamicMethods.pm

Typos detected by lintian whilst packaging 8.07 for Debian GNU/Linux

Fix typos in POD (lib/Mojo/DynamicMethods.pm)

---

lib/Mojo/ByteStream.pm
t/mojo/bytestream.t

Add support for the limit argument of Perl's split function to Mojo::ByteStream->split.
This PR contains both documentation and tests.
When processing character-delimited text files, a record may not have a value for it's ending fields and Perl's split function requires supplying a value for limit in order to retain those fields.
Additionally, according to the Perl manual, "In time-critical applications, it is worthwhile to avoid splitting into more fields than necessary."  As such, it makes sense to be able to override how many fields are actually processed.
Brief discussion on the mailing list with the subject "Mojo::ByteStream->split"

add limit argument to split function

---

lib/Mojolicious/Command/eval.pm
t/mojolicious/commands.t

I find the eval command to be invaluable for one-off usage and testing, especially while developing. As I've been writing more promise apis and now as I'm writing fewer blocking apis due to the existence of Mojo::AsyncAwait, I'm finding the usage of promises in the eval command to be cumbersome to the point of not using it. With this change, one that I doubt would affect any usage in the wild (who wants to dump the stringified promise?), we can make a very comfortable interface for one-off testing of promise apis and make for easy examples and demos for newcomers or answer-seekers on irc.

Add Mojo::Promise handling to the eval command

---

lib/Mojo/Promise.pm
t/mojo/promise.t

Adding a timeout method to avoid having to wrap Mojo::IOLoop->timeout(...) in a promise.
To make Mojo::Promise simpler to use in a generic usecase.
https://github.com/mojolicious/mojo/issues/1310#issuecomment-451748766

Add Mojo::Promise->timeout

---

lib/Mojo/Log.pm
t/mojo/log.t

If Time::HiRes::time returns an integer time (when the decimal component is 0) a warning is generated due to using the undef value in a string.
Prevent warnings
#1316

Allow for integer times in Mojo::Log default format (resolves #1316)

---

lib/Mojolicious/Renderer.pm
t/mojolicious/renderer.t

Implements a minimum size of the output for compression via an attribute
Compression can be counter-productive on small inputs both in terms of output size and CPU time.
Issue #1328

Add minimum size to renderer compression

---

lib/Mojo/Promise.pm
t/mojo/promise.t

Add a map method that allows delaying of portions of a set of promises so as to limit concurrency.

Add map class method to Mojo::Promise

---

lib/Mojo/Base.pm

Small documentation fix.  This was overlooked when -role was added.

four forms instead of three since -role got added

---

lib/Mojo/Promise.pm
t/mojo/promise.t

Ensure that `wait` will keep running the loop until the promise is no longer pending.
Calling `wait` can result in a still-pending promise even if the loop is not running, as anything may stop the loop. This small change ensures that it will not return while the promise is pending, which is the documented behavior and user expectation. This is also important for the proposed `get` method(s), to ensure it does not return before the results are available.
Prior art: the implementations of `await` and `get` in Future event loop subclasses will loop until the Future is no longer pending.

Wait for promise to resolve regardless of loop being stopped

---

lib/Mojo/UserAgent.pm
t/mojo/user_agent.t

Make sure to delete the timer from the connection cache too, not just
the ioloop, so the next request on the same connection will add its
timeout.

Fix Mojo::UserAgent request timeout on kept-alive connections

---

lib/Mojolicious/Guides/Cookbook.pod

Fix synchronizing non-blocking operations example.
Passing a Mojo::URL without scheme to Mojo::UserAgent->get(_p) does not work because the UA tries to fetch from localhost (see debug below).
This works:
`perl -Mojo -E 'say g("mojolicious.org")->dom->at("title")->text'`
This does not work:
`MOJO_CLIENT_DEBUG=1 perl -Mojo -E 'say g(Mojo::URL->new("mojolicious.org"))->dom->at("title")->text'`
Debug:
```
-- Blocking request (mojolicious.org)
-- Connect 8a1756fbe6b9d5bb3d50ea46f85350ab (http://127.0.0.1:42889)
-- Client >>> Server (http://127.0.0.1:42889/mojolicious.org)
GET /mojolicious.org HTTP/1.1\x0d
Content-Length: 0\x0d
User-Agent: Mojolicious (Perl)\x0d
Host: 127.0.0.1:42889\x0d
Accept-Encoding: gzip\x0d
\x0d
```
Maybe mojolicious should also support `g(Mojo::URL->new("<url without …

Fix synchronizing non-blocking operations example

---

lib/Mojolicious/Command/get.pm

The documentation for the get command has a missing "attributes" paragraph and instead had another form of description. Stock attributes paragraph was added and second form of description was merged with the original description.

Fix misplaced and missing paragraph in get command documentation

---

lib/Mojo/Promise.pm

Fall back to old behavior if more than one argument or hashref is given as argument
Maintain old behavior
As discussed on IRC.

Fall back to normal constructor if hash style arguments are provided

---

lib/Mojo/Server/Daemon.pm

Fixes a broken link in the Mojo::Daemon documentation.
Broken links are bad and non-useful
Reported in github issue #1356 by daxim

Fix broken link to cipher string list (#1356, thanks daxim)

---

lib/Mojolicious/Controller.pm

One of the examples for Mojo::URL->query behaviour was missed when it changed in 8.0. This corrects the example code.
I also did a (quick) check for other examples that may have been missed, but didn't find any more.
Examples in documentation should be correct.
Reported by yuki-kimoto (GitHub #1365).

Fix missed example for query behaviour change in 8.0 (yuki-kimoto)

---

.perltidyrc

The -nst option disables -st which is enabled by -pbp, which causes the tidied code to be written to STDOUT instead of a a new file suffixed with `.tdy`. This means only one file can be tidied at a time, and the -st option is also incompatible with the -b option, which allows updating files in place, a workflow well suited for git.
Instead of `perltidy lib/Some/File.pm > lib/SomeFile.pm.tdy`, now just do `perltidy lib/Some/File.pm` and multiple files can be specified in one command.
`perltidy -b lib/Some/File.pm` will update the file(s) in place and create lib/Some/File.pm.bak.
`perltidy -b -bext=/ lib/Some/File.pm` will update the file(s) in place and delete the backup file(s) as long as there were no errors.
To make it easier for contributors to run perltidy on their contributions. …

Add -nst to .perltidyrc

---

examples/chat.pl
examples/connect-proxy.pl
examples/entities.pl
examples/fast.pl
examples/hello-template.pl
examples/hello.pl
examples/microhttpd.pl
examples/proxy.pl
examples/responses.pl
lib/Mojo/Content.pm
lib/Mojo/Headers.pm
lib/Mojo/IOLoop/Stream.pm
lib/Mojo/Server/Daemon.pm
lib/Mojolicious/Controller.pm
lib/Mojolicious/Plugin/DefaultHelpers.pm
t/mojo/headers.t
t/mojo/ioloop.t
t/mojolicious/proxy_app.t

This is an implementation of the streaming proxy described in #1295.

Add streaming proxy feature

---

lib/Mojo/Server.pm

Fix usage of setsid
POSIX::setsid returns -1, not undef on failure:
```
❯ perl -MPOSIX -le 'my $ret = POSIX::setsid; print "$ret: $!"'
-1: Operation not permitted
```
N/A

fix usage of setsid

---

Makefile.PL

Prevent private packages from being indexed.
Packages starting with _ are not intended to be externally used or depended on, so they have no reason to be indexed on CPAN.
An alternative method is to put a newline after the 'package' keyword so PAUSE will ignore these packages, but this requires an exception for perltidy.

add private packages to no_index metadata

---

lib/Mojo/File.pm
t/mojo/file.t

It is currently very easy to delete the wrong directory by accident, like:
```perl
my $subdir = undef;
path('usr', 'share', $subdir)->remove_tree;
```
This would currently delete `usr/share` and only show a pretty insignificant warning about the `undef` value. I noticed the problem because we had a similar accident at work. 😉
```
$ perl -Mojo -E 'n { f("foo", "bar", "baz")->child("yada") } 1000000'
2.67053 wallclock secs ( 2.67 usr +  0.00 sys =  2.67 CPU) @ 374531.84/s (n=1000000)
$ perl -Ilib -Mojo -E 'n { f("foo", "bar", "baz")->child("yada") } 1000000'
2.80627 wallclock secs ( 2.81 usr +  0.00 sys =  2.81 CPU) @ 355871.89/s (n=1000000)
```
The performance cost is pretty minimal. I would have liked to include the empty string too, but unfortunately we depend on that currently for a …

Protect from undef values in Mojo::File objects

---

lib/Mojo/Collection.pm
lib/Mojolicious/Plugin/HeaderCondition.pm

Use [is_regexp](https://perldoc.pl/re#is_regexp($ref)) to detect regex refs instead of checking for ref 'Regexp'.
Regex refs created by qr// are actually blessed into the 'Regexp' class. ref 'Regexp' can be fooled by blessing random things into 'Regexp', or by reblessing the regex ref into something else. is_regexp will always detect the underlying regex ref.
https://github.com/mojolicious/mojo/pull/1377

use re::is_regexp to detect regex refs

---

lib/Mojo/Collection.pm
t/mojo/collection.t

Methods for Mojo::Collection to create new collections of the beginning or end of the collection.
Algorithms for the methods were adapted from [List::Util::PP](https://metacpan.org/pod/List::Util::PP). We could just delegate to List::Util for XS functions but it would require List::Util 1.50.
It can be useful to operate on the beginning or end of the collection during a chain without calculating slice indexes, and resulting in no extra undef elements when going past the original collection indexes.
https://github.com/mojolicious/mojo/issues/1350

head and tail methods for Mojo::Collection

---

.travis.yml

Switch to using build matrix to use `dist: trusty` for older perl versions.
Continue the testing of perl versions <5.22 on Travis, which are not available under xenial, now that is default.
* [build for bae2f75](https://travis-ci.com/mojolicious/mojo/jobs/221359883#L144-L189)
* [xenial as default](https://blog.travis-ci.com/2019-04-15-xenial-default-build-environment)
* travis-ci/perl-builder#8

Travis - use build matrix

---

lib/Mojo/JSON.pm
lib/Mojolicious/Command/version.pm
t/mojo/json_xs.t

Recent versions of Cpanel::JSON::XS throw an exception when decoding duplicate keys. allow_dupkeys was added in 4.09 to disable this behavior which is incompatible with Mojo::JSON.
Behavior compatibility with Cpanel::JSON::XS passthrough.

require Cpanel::JSON::XS 4.09+ for JSON speedup and set allow_dupkeys

---

lib/Mojo/Log.pm
lib/Mojolicious.pm
lib/Mojolicious/Controller.pm
lib/Mojolicious/Plugin/DefaultHelpers.pm
lib/Mojolicious/Plugin/EPLRenderer.pm
lib/Mojolicious/Renderer.pm
lib/Mojolicious/Routes.pm
t/mojo/log.t
t/mojolicious/group_lite_app.t
t/mojolicious/log_lite_app.t
t/mojolicious/renderer.t

This is one possible solution for #1400. The main goals were performance and simplicity. And there would be no backwards compatibility breakage.

Contextual logging

---

lib/Mojo/UserAgent.pm

Basic auth commonly uses username and password values from external sources, so they should be set using the Mojo::URL userinfo method rather than directly in the URL where they need to be escaped.
More correct example for a common use case
IRC discussion

set userinfo using Mojo::URL in Mojo::UserAgent Basic auth example

---

lib/Mojo/File.pm

Call Cwd::realpath directly, avoiding instantiating an intermediary Mojo::File object.
Optimization

Only create one Mojo::File object for curfile

---

lib/Mojolicious/Guides/Growing.pod

Fixes this error in Test::Mojo example code
> Can't locate object method "dirname" via package "curfile" ...
My perl version:
> This is perl 5, version 28, subversion 0 (v5.28.0) built for x86_64-linux

Fix Test::Mojo example code

---

lib/Mojo/Base.pm
t/mojo/roles.t

Allow `My::Class->with_roles()->new()`  # empty list
A) It doesn't hurt anything, and
B) I defined a base class that accepted an array of roles to [optionally] include...  When that list was empty, though, `with_roles()` caused the whole program to die.  :-(

With empty roles

---

.travis.yml

The version specification should hopefully avoid attempting to install this version that does not build on certain Travis CI images.
Allow CI to continue on all versions
*https://travis-ci.com/mojolicious/mojo/jobs/258411899
*http://www.cpantesters.org/cpan/report/7e952514-0b25-11ea-8efb-bf05dbb5ea62

Avoid broken EV version in Travis config

---

lib/Mojolicious/Command/get.pm
t/mojolicious/commands.t

The mojo get command still had an instance of the recently removed slice method. This replaces it with creating a new collection of that index since that's all it was doing.

fix mojo get index command to not rely on removed Mojo::Collection->slice

---

lib/Mojolicious/Types.pm
t/mojolicious/app.t
t/mojolicious/layouted_lite_app.t
t/mojolicious/lite_app.t
t/mojolicious/static_lite_app.t
t/mojolicious/types.t

Mojolicious::Types::content_type used to return `text/plain;charset=UTF-8`
for unknown types. Use `application/octet-stream` as default instead.
`Content-Type: text/plain;charset=UTF-8` may confuse browsers if returned
with binary data.
Fixes: mojolicious/mojo#1441

default to Content-Type: application/octet-stream

---

README.md
lib/Mojo/Base.pm
lib/Mojo/Promise.pm
lib/Mojolicious.pm
lib/Mojolicious/Command/version.pm
lib/Mojolicious/Guides/Cookbook.pod
t/mojo/promise_async_await.t
t/pod_coverage.t

For now this patch uses a frozen fork of `Future::AsyncAwait`, and the feature as a whole is marked as experimental. That will allow our users to start playing with `async`/`await`, and give @leonerd more time to figure out what he wants the stable `AWAIT_*` protocol to look like.

Add full async/await support to Mojolicious

---

lib/Mojo/Promise.pm
lib/Mojolicious.pm
t/mojo/promise_async_await.t

This is an alternative to #1452. It has the advantage that async functions work pretty much everywhere automatically. It does have the downside that it deactivates the `Future::AsyncAwait` feature for detecting unhandled promises however. So it becomes much easier to miss exceptions in async functions.

Allow for async functions to be used almost everywhere

---

lib/Test/Mojo.pm
t/mojolicious/app.t
t/mojolicious/lib/MojoliciousTest.pm
t/mojolicious/lib/MojoliciousTest/Foo.pm

Allow to test values of HTML attributes with test methods
In one of projects I need to test value in HTML attribute which is generated.
I don't like idea of concatenating strings in tests, so decided that having test methods for HTML attributes will be good addition to Test::Mojo

Add ability to test HTML attribute values with Test::Mojo

---

lib/Mojolicious/Plugin/DefaultHelpers.pm
lib/Mojolicious/Static.pm
t/mojolicious/app.t
t/mojolicious/static_lite_app.t

Add support in `is_fresh` for ETag and If-Modified-Since headers of the form `W/"foo"`.
Essentially, weak validation is not supported at all, and it is not easy to work around either:
1. It is not possible to use the `is_fresh` function to render a correct weak ETag, as they are rendered with double-quotes added, which would turn a call like `headers->etag('W/'.$checksum)` into `ETag: "W/abc"` instead of the correct `ETag: W/"abc"`.
2. It is not possible to use `is_fresh` to compare a calculated checksum of "abc" against a passed-in ETag of `W/"abc"`. One would have to perform the comparisons manually, essentially duplicating the functionality of `is_fresh`.
The specification and handling of weak etags are described here:
* https://en.wikipedia.org/wiki/HTTP_ETag#Strong_and_weak_validation …

add support for weakly-validating ETags

---

lib/Mojo/Base.pm
t/mojo/promise_async_await.t

Use `Test::Future::AsyncAwait::Awaitable` to test that `Mojo::Promise` conforms to the API expected by `Future::AsyncAwait`
This makes sure we don't accidentally break the `-async_await` feature.
As suggested by LeoNerd on IRC

Test that Mojo::Promise conforms to the Future::AsyncAwait::Awaitable API

---

lib/Mojolicious/Validator.pm
lib/Mojolicious/Validator/Validation.pm
t/mojolicious/validation_lite_app.t

This appears to be the default assumption of our users. The empty
string can now be validated with regexes and other checks.
Additionally non-browser users and form elements without any value
at all can now be considered during validation.

Change validation to consider the empty string a valid value

---

lib/Mojo/Message/Request.pm

Switch request_id from 8 hex characters to 8 base64url characters
8 characters is few enough that request ids repeat often enough to make log analysis on heavily used systems irritating sometimes ...
... but making the request id longer is kinda fugly and discussion in channel led to deciding we didn't want to do that ...
... but base64url gives 6 bits per character rather than 4, using [a-zA-Z0-9] plus '-' and '_' instead of '+' and '/' as normal base64, which IMO is still pretty damn readable ...
... and increases the number of theoretically possible request ids from 2^32 (4294967296) to 2^48 (281474976710656) ...
... and actually still looks nice to me:
$ for i in $(seq 1 10); do perl -Ilib -Mnew=Mojo::Message::Request -E 'say $O->request_id'; done
Tv02Ylba
H_aK5Lil
VKc-1hIN
CC-Ak9yx …

using base64url increases the request_id pool from 2^32 to 2^48

---

lib/Mojo/IOLoop/Stream.pm
lib/Mojo/Reactor.pm
lib/Mojo/Reactor/EV.pm
lib/Mojo/Reactor/Poll.pm
lib/Mojo/Server/Daemon.pm
lib/Mojo/Server/Hypnotoad.pm
lib/Mojolicious/Command/daemon.pm
lib/Mojolicious/Command/prefork.pm
t/mojo/daemon.t
t/mojo/hypnotoad.t
t/mojo/reactor_ev.t
t/mojo/reactor_poll.t

This patch is preparation for #1492. It adds a low level way to reset timers, which is much more efficient than completely replacing timers every time you want to change a setting like the `inactivity_timeout`.
Baseline, this is pretty much equal with and without patch (EV):
```
$ perl -Ilib -Mojo -E 'a(sub ($c) { $c->render(text => "Hello Mojo!") })->start' daemon -m production
Server available at http://127.0.0.1:3000
$ wrk -c 20 -d 10 http://127.0.0.1:3000
Running 10s test @ http://127.0.0.1:3000
2 threads and 20 connections
Thread Stats   Avg      Stdev     Max   +/- Stdev
Latency     9.46ms  735.87us  18.77ms   92.09%
Req/Sec     1.06k    44.73     1.15k    69.50%
21183 requests in 10.03s, 3.11MB read
Requests/sec:   2111.02
Transfer/sec:    317.85KB
````
With patch applied (EV):
``` …
```

Separate keep-alive and inactivity timeouts for all built-in web servers

---

lib/Mojo/IOLoop/Subprocess.pm
t/mojo/subprocess.t

Add promises support to Mojo::IOLoop::Subprocess.
#1496.

Add Mojo::IOLoop::Subprocess->run_p()

---

lib/Mojolicious/Guides/Tutorial.pod

A tutorial section for using plugins in applications.
Using plugins is not currently covered anywhere in the guides in a general manner.

Add plugin section to Tutorial guide

---

lib/Mojo/Promise.pm
lib/Mojolicious/Plugin/DefaultHelpers.pm
t/mojo/promise.t

This is an implementation for #1454. I think it covers all use cases, but handling multiple branches with promise chains and `$promise->wait` correctly makes my head hurt a bit.
```
$ perl -Ilib -Mojo -E 'Mojo::Promise->reject("something bad")'
Unhandled rejected promise: something bad at -e line 1.
```

Make unhandled rejected promises warn

---

.github/workflows/linux.yml

On Perl 5.18 and older, `cpanm --installdeps` was not picking up `Sub::Util` and `IO::Socket::IP` properly, and updating `ExtUtils::MakeMaker` fixes it.  I included an update of `App::cpanminus` just for good measure.
Fixes #1508 :smile: :birthday:
See #1508 for more details, especially https://github.com/mojolicious/mojo/issues/1508#issuecomment-634247300. :+1:

Pre-upgrade "App::cpanminus" and "ExtUtils::MakeMaker"

---

t/mojo/date.t

Tests for `Mojo::Date` in `t/mojo/date.t` converted to subtests.
Another file converted.
#1520.

Convert t/mojo/date.t to use subtests

---

lib/Mojo/Template.pm
t/mojo/template.t

When `end` and `begin` occur on the same perl line or mix-line group, the presence of the `begin` token causes the `end` token to incorrectly be followed by a `;` which breaks expectations, is hard to work around, and is generally incorrect as it is still valid in theory.

Allow end and begin to occur on the same template line

---

lib/Mojo/Promise.pm

One of the method calls in Mojo::Promise's synopsis was missed when it was changed to more thoroughly demonstrate the use of promises. This PR just corrects it. The synopsis has been tested and works after this fix (seems like metacpan.org always wins though! :stuck_out_tongue:).
Issue report by dmanto #1535

Correct method call in Mojo::Promise synopsis, closes #1535

---

lib/Mojolicious/Plugin/DefaultHelpers.pm
t/mojolicious/proxy_app.t

`proxy.start_p` misbehaves when it receives the headers only, with a zero-length body. It naively calls `$content->write(pop)` with that zero-length body, and "writ[ing] an empty chunk of data at any time [ends] the stream".
I believe this is not the intended behaviour. This PR has a test that captures this behaviour, and a patch to eliminate it.
`#mojo` discussion over the last couple of weeks with @Grinnz and @CandyAngel (thanks!).

Make proxy.start_p work on initial empty body

---

lib/Mojolicious.pm
t/mojolicious/dispatcher_lite_app.t

Currently Controller->render_later has no effect if called from before_dispatch hook.
This blocks delayed rendering for tasks which don't have pre-defined routes, e.g. Mojolicious-Plugin-Directory
It looks that documentation doesn't forbid Controller->render_later in before_dispatch.
With proposed change delayed rendering from before_dispatch seems to work properly.

Allow render_later in before_dispatch

---

lib/Test/Mojo.pm
t/mojolicious/app.t
t/mojolicious/lib/MojoliciousTest/Foo.pm

Make `attr_is` test work with falsy values.

fix attr test for falsy values

---

lib/ojo.pm
t/mojolicious/ojo.t

Little `l` has been feeling left out recently, many of the other letters are happy doing jobs in the `ojo` world, he would like to join in the fun and help convert strings to `Mojo::URL` objects.
Give `l` a job and help with code in the POD.
I asked sometime last year about this on IRC, IIRC `Mojo::Autobox` was suggested, but this seems more simple, less deps.
#1514 has raised it again.

Add l for link to ojo

---

lib/Mojolicious/Guides/Cookbook.pod

Fix the example about EventSource in the Cookbook.
When using the example for EventSource in the Cookbook, closing one of the listeners triggers an error because the callback expects at least parameter `$code` but receives only the Controller instance.
None
The original example in the Cookbook for EventSource has this:
$c->on(finish => sub ($c, $code, $reason = undef) {
$c->app->log->unsubscribe(message => $cb);
});
This is probably a copy-and-paste from the WebSocket example, but the "finish" event that is emitted by Mojo::Transaction does not provide any parameter, which makes the above call fail with an error on the number of arguments.

Fix calling of finish in EventSource example

---

lib/Mojo/Promise.pm

I'm not 100% sure about this feature, but it seems pretty useful for locating your unhandled rejected promises.
Instead of
```
Unhandled rejected promise: branches3 at /Users/sri/repo/mojo/lib/Mojo/Reactor/Poll.pm line 131.
```
you would see
```
Unhandled rejected promise: branches3 at /Users/sri/repo/mojo/lib/Mojo/Reactor/Poll.pm line 131.
-- Destroyed promise
Traceback (most recent call first):
File "/Users/sri/repo/mojo/lib/Mojo/Promise.pm", line 55, in "Mojo::Promise"
File "/Users/sri/repo/mojo/lib/Mojo/Promise.pm", line 94, in "Mojo::Promise"
File "t/mojo/promise.t", line 444, in "main"
File "/Users/sri/perl5/perlbrew/perls/perl-5.32.0/lib/site_perl/5.32.0/Test/Builder.pm", line 374, in "Test::Builder"
File "/Users/sri/perl5/perlbrew/perls/perl-5.32.0/lib/site_perl/5.32.0/Test/Builder …
```

Add MOJO_PROMISE_DEBUG environment variable

---

t/mojo/daemon.t

- Convert `t/mojo/daemon.t` to use subtests
- Another file converted.
#1520

Convert t/mojo/daemon.t to use subtests

---

lib/Mojolicious/Guides/FAQ.pod

Add a faq entry for the error received when trying to follow examples with signatures without enabling the signatures feature.
Signatures from examples can get interpreted as prototypes and it's not immediately clear the signatures feature is required, especially for users not familiar with signatures or prototypes.

Add FAQ entry for prototype error when not using signatures

---

t/mojo/ioloop.t

Tests for `Mojo::IOLoop` in `t/mojo/ioloop.t` converted to subtests.
On going effort.
#1520

Convert ioloop.t to subtests

---

lib/Mojo/IOLoop.pm
t/mojo/ioloop.t

No longer trigger close event for streams when resetting the ioloop.
This fixes the bug where child processes have such cleanup events triggered.
- #1563

Unsubscribe close events for streams when resetting ioloop

---

t/mojo/delay.t

Convert t/mojo/delay.t to use subtests.
Issue #1520

Convert t/mojo/delay.t to use subtests

---

t/mojo/home.t

Convert t/mojo/home.t to use subtests.
Issue #1520

Convert t/mojo/home.t to use subtests

---

t/mojo/reactor_detect.t

Convert t/mojo/reactor_detect.t to use subtests.
Issue #1520

Convert t/mojo/reactor_detect.t to use subtests

---

lib/Mojolicious/Command/eval.pm

This is a fixed version of PR#1576 with consistent syntax to allow a clean merge.
suppresses a superfluous warning when using the "eval" command with a Mojolicious::Lite app
This came up when preparing an internal workshop about Mojolicious.
When I use even a minimal Mojolicious::Lite app as follows (say `myapp-lite.pl`):
```perl
#!perl
use Mojolicious::Lite;
app->start;
```
running `./myapp-lite.pl eval` will issue a warning: `Subroutine main::app redefined at (eval 109) line 1.`
With the equivalent full app (say `myapp-full.pl`):
```perl
#!perl
use Mojo::Base qw(-strict);
package MyApp { use Mojo::Base 'Mojolicious'; }
use Mojolicious::Commands;
Mojolicious::Commands->start_app('MyApp');
```
running `./myapp-full.pl eval` will issue no such warning.
A more realistic example like …

subroutine main::app intentionally redefined for "eval" command

---

t/mojo/json_pointer.t

Convert t/mojo/json_pointer.t to use subtests.
Issue #1520

Convert t/mojo/json_pointer.t to use subtests

---

t/mojolicious/exception_lite_app.t

As the title says.
I was already in the area for #1578 so might as well convert the test!
For #1520.

Convert t/mojolicious/exception_lite_app.t to use subtests

---

t/mojolicious/websocket_lite_app.t

Switching test suite to using subtests
As discussed in issue #1520

Websocket Lite app test uses subtests

---

t/mojo/psgi.t

Converting more tests files to using subtests
As discussed in issue #1520

convert t/mojo/psgi.t to using subtests

---

t/mojo/request.t
t/mojo/request_cgi.t

Tests for `Mojo::Message::Request` in `t/mojo/request.t` and `t/mojo/request_cgi.t` converted to use subtests.
Continuing ongoing effort
#1520

Convert request.t and request_cgi.t to subtests

---

lib/Mojolicious/resources/public/mojo/highlight.js/highlight.min.js

While working on https://github.com/mojolicious/mojolicious.org/pull/22 I was alerted about https://github.com/highlightjs/highlight.js/releases/tag/10.3.2
As we're using a custom build that's supposed to include JavaScript, we rebuild this here from https://highlightjs.org/download/ to make sure.
For comparison, here's our current highlight.js version (10.3.1), mistaking the JS snippet for `bash`:
And here is the latest (10.3.2) which fixes it:
The highlighting itself does not change though, but I figure it is better to ensure code blocks are properly recognized.
#1578 
For additional record, the highlight.js custom build contains support for these languages:
- bash
- CSS
- diff
- HTML, XML
- JSON
- JavaScript
- Perl
- plain text
- SQL

Bump Highlight.js to 10.3.2

---

lib/Mojo/Template.pm

Just a simple capitalization issue. 
When I try the example, the error message has "SandBox" instead of "Sandbox".

'Sandbox' -> 'SandBox'

---

lib/Mojolicious/Command/Author/generate/dockerfile.pm
lib/Mojolicious/Commands.pm
lib/Mojolicious/Guides.pod
t/mojolicious/commands.t

This adds a very basic implementation of `./script/myapp generate dockerfile` - enough to get users started quickly.
Docker is a simple and useful way to deploy software, and we might as well help users get started!
Closes #1600
(As always, happy to rebase, amend, force push, close, defer, discuss, etc ❤️)

Add initial dockerfile generator

---

lib/Mojo/Util.pm

By immediately returning when the two strings are not the
same length, the function allows an attacker to guess the
length of the secret string using timing attacks.
This change uses a fix by @jberger, based on [1].
This also updates the documentation to emphasize that the
secret string should be the second argument (although it's
not critical).
[1] https://github.com/vadimdemedes/secure-compare/blob/master/index.js
This fixes a potential leak of the length of the secret string using timing attacks.
The secure_compare function is not as secure as claimed.
See discussion #1599.

Mojo::Util#secure_compare fix leak of string length #1599

---

.github/workflows/windows.yml

Refs:
- https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-commands-for-github-actions#environment-files
- https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-commands-for-github-actions#adding-a-system-path.
This is as mentioned on IRC:
> \<@kraih\> our windows setup for github actions is broken and needs to be updated https://github.com/mojolicious/mojo/pull/1611/checks?check_run_id=1411922741
:heart:
(As always, happy to update, rebase, amend, adjust, discuss, close, etc)

Fix Windows GitHub Action (GITHUB_PATH env vs add-path command)

---

lib/Mojolicious/Commands.pm
t/mojolicious/commands.t

Resolves the bug where help is not shown for commands with a dash.
Consistency
#1610

Display help for dash commands as per hint

---

lib/Mojo/Promise.pm
t/pod_coverage.t

Adds new named method for latest `Future::AsyncAwait::Awaitable` role API specification.
Future::AsyncAwait will expect this new name in a later version.
https://metacpan.org/pod/Future::AsyncAwait::Awaitable#AWAIT_ON_CANCEL

Provide (empty) Mojo::Promise::AWAIT_CHAIN_CANCEL method

---

lib/Mojo/Loader.pm
lib/Mojolicious.pm
t/mojo/file.t
t/mojo/lib/Mojo/LoaderTest/A.pm
t/mojo/lib/Mojo/LoaderTest/B.pm
t/mojo/lib/Mojo/LoaderTest/C.pm
t/mojo/lib/Mojo/LoaderTest/D.txt
t/mojo/lib/Mojo/LoaderTest/E/F.pm
t/mojo/lib/Mojo/LoaderTest/E/G.txt
t/mojo/lib/Mojo/LoaderTestException/A.pm
t/mojo/loader.t
t/mojolicious/app.t

This is a less ambitious solution for #1607. It doesn't preload all possible controllers but leaves it up to the developer to configure the right namespaces. The default of `MyApp::Controller` might just work for most of our users though.
More efficient memory usage. Detecting syntax errors in controllers much earlier (during application startup instead of at runtime).
#1607

Add framework for preloading controllers

---

lib/Mojolicious/Routes/Pattern.pm
t/mojolicious/pattern.t

The type_start character passed to split is currently being treated as a regex but it should be treated as a string to split on.
The type_start attribute is meant to be a single character that delimits a placeholder name from its type. It was being
passed directly to split and thus used as a regex, which means any regex metacharacters would break the parsing.
Interpolate it with \Q to apply quotemeta to the character for use in split, and add tests for custom placeholder
characters.

Treat type_start in Mojolicious::Routes::Pattern as a character instead of a regex

---

lib/Mojo/Exception.pm
lib/Mojo/Home.pm
lib/Mojo/JSON.pm
lib/Mojo/JSON/Pointer.pm
lib/Mojo/Loader.pm
lib/Mojo/Parameters.pm
lib/Mojo/Path.pm
lib/Mojo/Server/Daemon.pm
lib/Mojo/Template.pm
lib/Mojo/Transaction/WebSocket.pm
lib/Mojo/UserAgent.pm
lib/Mojo/UserAgent/Proxy.pm
lib/Mojo/Util.pm
lib/Mojolicious/Command.pm
lib/Mojolicious/Command/Author/generate/plugin.pm
lib/Mojolicious/Renderer.pm
lib/Mojolicious/Routes/Pattern.pm
lib/Mojolicious/Static.pm
lib/Mojolicious/Types.pm
t/mojo/file.t

Use `split /PATTERN/` rather than `split 'STRING'` where appropriate.
As described in its [documentation](https://perldoc.perl.org/functions/split), the first argument to split is a pattern, not a string. Even if a string is passed, it is used as a pattern. Thus using the `/PATTERN/` syntax makes it clear to the reader that it is a regex and not a string.
Note that `split ' '` (single space string) is an exception where a string must be passed to activate awk compatibility, so we leave this case alone. Also, Mojo::ByteStream's split method cannot take a bare `/PATTERN/` because in that case it would be interpreted as an immediate regex match against `$_`.
https://perldoc.perl.org/functions/split

Use split /PATTERN/ syntax consistently

---

.github/workflows/rebuild-website.yml

Now that as of https://github.com/mojolicious/mojolicious.org/pull/23 the website can be automatically built and deployed, this PR adds the ability to trigger the website rebuild when pushes are made to the master branch of mojolicious itself.

Add workflow that triggers the website to rebuild

---

lib/Mojolicious/Commands.pm
t/mojolicious/commands.t

Top level `mojo help` subcommand is currenlty returning `Invalid command 'help'` instead of usage and available subcommands.
Bring back usage and command list functionality.
This closes #1629

allow top-level help command to output usage and list available commands

---

lib/Mojo/IOLoop.pm
lib/Mojo/IOLoop/Subprocess.pm
t/mojo/ioloop.t

This is a possible solution for #1563. It sidesteps the original problem by keeping all the original state active, but hidden away. The event loop is reset with a fresh reactor instance. In the case of `Mojo::Reactor::EV` this means that all subprocesses will end up with `Mojo::Reactor::Poll`. Which is probably an advantage.

Prevent unintended subprocess side effects by freezing the current state

---

lib/Mojolicious/Guides/Rendering.pod

Explicitly document how to change the HTTP return code for exceptions
It's not as obvious to newcomers.
This closes #1622.

Document how to change the HTTP status code for an exception

---

lib/Mojo/Message/Request.pm
lib/Mojo/Server.pm
lib/Mojo/Server/Hypnotoad.pm
lib/Mojo/Transaction.pm
lib/Mojo/Util.pm
lib/Mojolicious/Command/daemon.pm
lib/Mojolicious/Command/prefork.pm
lib/Mojolicious/Guides/Cookbook.pod
t/mojo/cgi.t
t/mojo/hypnotoad.t
t/mojo/psgi.t
t/mojo/util.t
t/mojolicious/commands.t
t/mojolicious/lite_app.t

Both when using self-hosted kubernetes with ingresses and using external cloud proxy services, it is useful to have the ability mark certain proxies as trusted, ignoring their entries in the X-Forwarded-For header and getting the true client's ip address. While there are plugins on CPAN that can do this, those are hard to add to existing pre-built applications which would have to load them, and their mechanism to do so (hooks and rewriting) is heavier that what can be done in core (during message parsing).
This PR adds this ability to core, keeping the implementation as simple as possible and using only core libraries.

Trusted proxy handling to existing reverse proxy functionality

---

lib/Mojolicious/Command/daemon.pm
lib/Mojolicious/Command/prefork.pm
t/mojolicious/commands.t

The golfing of the daemon and prefork commands was too aggressive and it meant that command line invocations essentially could not use the environment variables.

Accept MOJO_TRUSTED_PROXIES when -p is not given

---

t/mojolicious/longpolling_lite_app.t

convert `t/mojolicious/longpolling_lite_app.t` to use subtests

convert t/mojolicious/longpolling_lite_app.t to use subtests

---

lib/Mojo/Message/Request.pm
lib/Mojo/Server.pm
lib/Mojo/Server/Hypnotoad.pm
lib/Mojo/Util.pm
lib/Mojolicious/Command/daemon.pm
lib/Mojolicious/Command/prefork.pm
t/mojo/cgi.t
t/mojo/hypnotoad.t
t/mojo/psgi.t
t/mojo/util.t
t/mojolicious/commands.t
t/mojolicious/lite_app.t

As seen in https://github.com/mojolicious/mojo/runs/1912645557
apparently a change to Socket on windows meant that these addresses were
no longer parsing correctly. While they're convenient they're not
required. This change no longer allows them on any platform.

Disallow short-form ipv4 networks

---

t/mojolicious/layouted_lite_app.t

convert `t/mojolicious/layouted_lite_app.t` to use subtests

convert t/mojolicious/layouted_lite_app.t to use subtests

---

lib/Mojolicious.pm

Just a small change to reuse $stash variable in dispatch() I found while reading through the code.
I hope it is not too annoying for the mojo team to submit a PR for this simple change.

reuse $stash variable in dispatch

---

lib/Mojo/Message/Request.pm

This change is a minor tweak to the documentation for `Mojo::Message::Request` to fix a recent documentation error introduced as part of IPv4 short-form address removal in commit e3af2e7b4b.
This fix added too many octets when inflating an address to normal form, resulting in the invalid address of 172.16.0.0.0/12.
I fix the fix by removing the extra octet to leave 172.16.0.0/12.
The issue is minor, but documentation errors may tend to introduce concern on the part of the reader, and this seems to be reflected in other Mojo core team commits to make occasional documentation cleanups after new features or important changes until the docs are clear and easy to understand and apply.
To look for other potential documentation flaws I ran a scan of the entire Mojolicious repository looking for …

doc: Cleanup ipv4 address expansion from short form.

---

t/mojo/morbo.t

Import fewer symbols in morbo.t
With this change, the tests should continue to pass, but the number of
symbols found goes from 612 to 444 according to:
```perl
use Symbol::Get ();
my @symbols = Symbol::Get::get_names();
diag 'found ' . @symbols . ' symbols';
```
As far as I can tell, there's no need to:
```perl
use IO::Socket::INET;
use Socket qw(SO_REUSEPORT SOL_SOCKET);
```
`IO::Socket::INET` isa `IO::Socket` and does not have its own `import()`. If
`IO::Socket::import()` is called without any arguments, it exports
directly from `Socket`
https://metacpan.org/source/TODDR/IO-1.45/lib/IO/Socket.pm#L38
`Socket` exports a large number of symbols by default, including
`SO_REUSEPORT` and `SOL_SOCKET`. So, what appears to be happening is that
the `use Socket` statement avoids importing a lot …

Import fewer symbols in morbo.t

---

lib/Mojolicious/Validator.pm

Update to the documentation that seems to have been missed for new `comma_separated` filter.
Up to date docs.
None

Add missing reference to comma_separated filter in POD

---

lib/Mojolicious/Guides/Cookbook.pod

Add example User settings in the service file examples for deployment.
Mojolicious servers default to deploying to ports 3000 and 8080, which don't require elevated privileges, so starting the service as a regular user is a better default suggestion.
https://www.freedesktop.org/software/systemd/man/systemd.exec.html#User/Group%20Identity

Mojolicious::Guides::Cookbook - Include User settings in example services files

---

lib/Mojolicious/Guides/Testing.pod

Include the example from Test::Mojo/new to show how to load a Mojolicious::Lite application with Test::Mojo.
The guide does not currently specify how to test a Mojolicious::Lite application which doesn't have an application class.

Mojolicious::Guides::Testing - mention how to test Mojolicious::Lite applications

---

Makefile.PL
lib/Mojolicious/Guides.pod
lib/Mojolicious/Guides/Contributing.pod
lib/Mojolicious/Guides/Cookbook.pod
lib/Mojolicious/Guides/FAQ.pod
lib/Mojolicious/Guides/Growing.pod
lib/Mojolicious/Guides/Rendering.pod
lib/Mojolicious/Guides/Routing.pod
lib/Mojolicious/Guides/Testing.pod
lib/Mojolicious/Guides/Tutorial.pod
lib/Mojolicious/resources/templates/mojo/debug.html.ep

Replace references to the freenode channel with libera.chat
IRC channel is moving
https://www.kline.sh/

The #mojo channel is moving to libera.chat

---

Makefile.PL
lib/Mojolicious/Guides.pod
lib/Mojolicious/Guides/Contributing.pod
lib/Mojolicious/Guides/Cookbook.pod
lib/Mojolicious/Guides/FAQ.pod
lib/Mojolicious/Guides/Growing.pod
lib/Mojolicious/Guides/Rendering.pod
lib/Mojolicious/Guides/Routing.pod
lib/Mojolicious/Guides/Testing.pod
lib/Mojolicious/Guides/Tutorial.pod
lib/Mojolicious/resources/templates/mojo/debug.html.ep

Use https://web.libera.chat/#mojo for webchat links and metadata.
Simpler links using the official libera.chat webchat

Update webchat links to web.libera.chat

---

lib/Mojolicious/Sessions.pm
t/mojolicious/lite_app.t

Pad the session value to at least 1025 bytes. This should prevent a small value from being used as part of a brute-force attack to decode the session secret.

pad session values to 1025 bytes by default

---

lib/Mojo/IOLoop.pm

The example from the Mojo::IOLoop page needs '-signatures',
and even with '-signatures' it fails with
Mojo::Reactor::Poll: I/O watcher failed: Too many arguments for subroutine 'main::__ANON__' at /usr/local/share/perl5/5.32/Mojo/IOLoop.pm line 112.
because the server handler gets third argument - the $id.

Mojo::IOLoop example fix (minor)

---

lib/Test/Mojo.pm
t/mojolicious/app.t
t/mojolicious/lib/MojoliciousTest/Foo.pm

Return undef instead of empty string for nonexistent _attr and _text selectors in tests.
This can be helpful to prevent tests with a typo in the selector from passing.
For example this test will now fail (notice the typo):
`$t->attr_is('form inputt[name=user]', 'value, '');`

return undef for nonexisting _attr and _text selectors in tests

---

lib/Mojo/DOM/HTML.pm
t/mojo/dom.t

This is a tentative to fix #1536 by not crossing container element while going up the tree to auto-close other tags.
Seemed easy to fix. But then I’m sure that there are plenty of edge cases that I didn’t think of, feel free to suggest tests to add here.
#1536

Do not close paragraphs due to div inside svg or mathml.

---

t/mojo/proxy.t
t/mojo/subprocess.t
t/mojo/user_agent_tls.t
t/mojo/user_agent_unix.t

Here are four more test files converted to use subtests as per issue #1520.

Convert to using subtests per issue #1520

---

lib/Mojolicious/Guides/Cookbook.pod

Fix two bugs in the Cookbook.pod (examples)
Any student who want to learn more about Mojolicious should have a bugfree experience
bug 1.)  Mojolicious -> hook -> after_build_tx
bug 2.) Mojolicious::Cotroller -> on -> finish

Fix two bugs in the Cookbook.pod

---

lib/Mojolicious/Guides/Testing.pod

Reword the paragraph explaining the same code but with two different approaches.
The way the paragraph is written now may lead the reader to think that explanation is valid only for one of the snippets instead of the two it's actually referring to. To avoid it, slightly change the first sentence.

doc: reword testing guide paragraph

---

lib/Mojolicious/Guides/Growing.pod

Remove very and capitalize ID
Remove 'very' as it's frowned upon in English style guides and not contributing much to these sentences.
ID should be be capitalized according to English guides. I'd say the exception would be when we're directly referring to an 'id' attribute in markup.
https://www.forbes.com/sites/katelee/2012/11/30/mark-twain-on-writing-kill-your-adjectives/
https://english.stackexchange.com/questions/101248/how-should-the-abbreviation-for-identifier-be-capitalized
Originally raised in https://github.com/mojolicious/mojo.js/pull/44

Minor tweaks to Growing guide.

---

lib/Mojolicious/Guides/Growing.pod

Fix a couple of grammar issues in Testing section
The adjective state-of-the-art should be written with dashes, and we should use the adverb seriously in this context.
https://writingexplained.org/state-of-the-art-vs-state-of-the-art

More grammar fixes for Growing guide

---

t/mojolicious/command.t

The file `t/mojolicious/command.t` has been organised into subtests, and spacing added to create blocks within.
Note that the following variables were originally global, but have now been scoped to each subtest requiring them:
* `$buffer`
* `$template`
* `$command`
* `$cwd`
* `$dir`
Towards resolution of #1520
Refer to discussion in #1520

Convert t/mojolicious/command.t to use subtests

---

t/mojo/ioloop_ipv6.t

Tests in `t/mojo/ioloop_ipv6.t` converted to use subtests.
Help convert remaining subtests.
#1520

Convert t/mojo/ioloop_ipv6.t to use subtests

---

lib/Mojolicious/Plugin/TagHelpers.pm

In the `link_to` documentation, add a sentence explaining why, in the examples, sometimes there is a title given first, and sometimes a block of code or a template block as the final argument.
Without an explanation, some folks (e.g., me) may be confused about the correct or possible ways to call or use `link_to`… the truly devoted (or truly stubborn; me again) may even resort to deciphering the Mojo source to see what's really going on.

Clarify link_to arguments

---

lib/Mojo/Exception.pm
t/mojo/exception.t
t/mojo/template.t

This should fix the situation with traceback produced by Mojo::Exception much less informative than traceback produced by Carp
```
exception: raise at /home/agrechkin/tmp/test-exception line 9.
Traceback (most recent call first):
File "/home/agrechkin/tmp/test-exception", line 9, in "main"
File "/home/agrechkin/tmp/test-exception", line 12, in "main"
File "/home/agrechkin/tmp/test-exception", line 24, in "main"
File "/home/agrechkin/tmp/test-exception", line 29, in "main"
exception: croak at /home/agrechkin/tmp/test-exception line 17.
eval {...} called at /home/agrechkin/tmp/test-exception line 20
main::carp_croak() called at /home/agrechkin/tmp/test-exception line 25
main::main() called at /home/agrechkin/tmp/test-exception line 29
```
Closes: #1947

traceback in Mojo::Exception print fully qualified sub names

---

lib/Mojolicious.pm
t/mojolicious/dispatcher_lite_app.t

If rendering happened in before_dispatch (e.g. dynamic paths were processed), no need to try to render with static or find a route.
If before_dispatch sets 'rendered' flag, further actions around static and routes not only waste of resources, but may also finish rendering, which will suppress delayed rendering from before_dispatch
#1534

Finish rendering early in Mojolicious::dispatch

---

lib/Mojo/Promise.pm
t/mojo/promise_async_await.t

This PR will avoid warning "Unhandled rejected promise warning" when using async/await and a promise gets rejected.
I think this change is correct after reading https://metacpan.org/pod/Future::AsyncAwait::Awaitable#AWAIT_DONE where it says "...result of an existing still-pending future", which means there's no reason to create new promise objects.
Less warnings.

Avoid "Unhandled rejected promise warning" when using async/await

---

lib/Mojo/Promise.pm
t/mojo/promise_async_await.t

Fix issue introduced in 166cedb244009e956bd8c3de16d86292bb0f59ee when an async method returns a promise.
@jberger reported the issue.
166cedb244009e956bd8c3de16d86292bb0f59ee

Fix handling returned $promise from async method, closes #1990

---

.github/workflows/linux.yml

This PR will run t/mojo/promise_async_await.t in the GitHub workflow.
On Sunday I pushed a bad commit to #1991, which of course I should've noticed locally, but it would be nice to get feedback from github as well. I think that will make it easier to review related PRs as well.

Will run async/await tests in github linux workflow

---

lib/Mojo/UserAgent.pm

Eliminate warnings generated by `t/mojolicious/websocket_lite_app.t`.
Before this patch:
```
$ prove -l t/mojolicious/websocket_lite_app.t 
t/mojolicious/websocket_lite_app.t .. 1/? Use of uninitialized value $loop in hash element at /tmp/mojo/lib/Mojo/UserAgent.pm line 201.
Mojo::Reactor::Poll: I/O watcher failed: Can't call method "remove" on an undefined value at /tmp/mojo/lib/Mojo/UserAgent.pm line 291.
t/mojolicious/websocket_lite_app.t .. ok    
All tests successful.
Files=1, Tests=35,  1 wallclock secs ( 0.04 usr  0.02 sys +  0.51 cusr  0.06 csys =  0.63 CPU)
Result: PASS
```
After this patch:
```
$ prove -l t/mojolicious/websocket_lite_app.t 
t/mojolicious/websocket_lite_app.t .. ok    
All tests successful.
Files=1, Tests=35,  1 wallclock secs ( 0.04 usr  0.01 sys +  0.49 cusr …
```

eliminate warning reported by #1739

---

lib/Mojolicious/Guides/Cookbook.pod

`wss://ws.postman-echo.com/raw` is a drop-in replacement for this example that works.
`ws://echo.websocket.org` service no longer available  ([http://echo.websocket.org](http://echo.websocket.org))
None.

echo.websocket.org service no longer available

---

lib/Mojo/Server/Daemon.pm

This patch logs the handle's `peerpath` if the handle is a `IO::Socket::UNIX` object, otherwise logs the handle's `peeraddr`.
The server fails when debugging a server listening on a unix domain socket because a `IO::Socket::UNIX` object does not have a `peerhost` method.  This patch retains existing functionality except when the handle is an `IO::Socket::UNIX` object (i.e. listening on a unix domain socket).
MOJO_SERVER_DEBUG=1 fails with UNIX domain sockets #1980.

fix UNIX domain socket debugging reported by #1980

---

lib/Mojo/UserAgent.pm
t/mojo/user_agent_tls.t

My use case is that I need to communicate with a server which uses a too small DH key (OpenSSL error "tls_process_ske_dhe:dh key too small") but I do not want to manipulate the cipher list globally (e.g. via `IO::Socket::SSL::set_defaults( SSL_cipher_list => 'DEFAULT:!DH@SECLEVEL=1' )`). This probably lacks a test but I'm not really sure how a test would look which actually confirmed that TLS behaviour was successfully manipulated via an option.

Allow setting TLS options for connections in Mojo::UserAgent

---

lib/Mojolicious/Plugin/DefaultHelpers.pm
t/mojolicious/proxy_app.t

This patch allows proxying empty body responses such as those with code 200 and length 0, and, more importantly, 301 and 302 redirects with length 0.
While this patch still passes all tests -- as well as the 12 tests added -- I don't know if this solution is acceptable and in the spirit of the comment that was there.  It seems the conditional that is currently used is insufficient, and I don't know what would be better; moreover, no tests fail with this change.
The gateway (proxy) server using `proxy->start_p` is unable to successfully handle redirects received from the origin (backend) server.
proxy->start_p helper doesn't forward empty body responses #2008.

forward empty body responses as reported by #2008

---

lib/Mojolicious/Guides/Cookbook.pod

Set the correct namespace in example code and also change the example route to be `/` instead of `/welcome` so that the test generated by the Cookbook's example running `mojo generate app MyApp` works.
Make example code more ready-to-use.
None.

Set correct namespace in example code

---

lib/Mojo/Promise.pm
t/mojo/promise_async_await.t

Before this commit:
> Rejected promise at Mojo/Promise.pm line 23.
After this commit:
> Rejected promise at t/mojo/promise_async_await.t line 88.
I think it would be useful to see where the promise was rejected.

Improved "at ... line ..." reporting for rejected async method

---

lib/Mojo/IOLoop/Client.pm
lib/Mojo/IOLoop/TLS.pm
lib/Mojo/JSON.pm
lib/Mojo/Util.pm

eval in list context returns empty list when it fails, not undef. List context includes "use constant" because list constants unfortunately exist.
We want to ensure no danger of bugs due to context sensitivity.
#2051

ensure eval is always called in scalar context (#2051)

---

lib/Mojolicious/Plugin/DefaultHelpers.pm
t/mojolicious/exception_lite_app.t

**Summary**
Make it easier to use exceptions, when exception format is not HTML
**Motivation**
It doesn't make sense for exceptions to be stored in the stash only if the format is HTML, instead it makes more sense, and is more consistent to store them in the stash for all formats
**References**
fixes #2048 
I annihilated my branch on the other PR like a goof #2061 and github auto closed the PR because of it.

Add exceptions to stash regardless of format

---

lib/Mojo/Server/Prefork.pm

If the worker reports itself as shutting down, do not second another SIGQUIT to the worker. It already knows it is shutting down, and this can cause a race with signal handlers that triggers coredumps.
Full writeup in #2046
The short version:
- When a worker receives a SIGQUIT, it begins to gracefully shut down
- During graceful shutdown, the worker notifies the manager thread of its shutdown
- If the manager sent the initial SIGQUIT, then it already knows the worker is shutting down and takes no action
- If the manager did not send the initial SIGQUIT, then it marks the worker for graceful shutdown, causing it to send a second SIGQUIT
- This second SIGQUIT can arrive once Perl has already de-registered the QUIT signal handler, which causes it to perform the default QUIT action (coredump) …

Do not send redundant SIGQUITs

---

lib/Mojo/Promise.pm
t/mojo/promise.t

The check for whether to call the callback returned early if the item was falsy.  Instead, it needs to only return early if there are no items left.

Fix Promise->map hang on false values after concurrency limit

---

lib/Mojo/File.pm
t/mojo/file.t

Alter Mojo::File to:
* Allow slurp and decode with ```$file->slurp('UTF-8');``` etc.
* Allow spew and encode with ```$file->spew('contents', 'UTF-8');``` etc.
As we discussed on IRC, allowing these options not only makes it easier for users as well as bring things more inline with what is allowed in the Mojo.js framework.

Allow selection of an encoding on slurp/spew in Mojo::File

---

lib/Mojo/Server.pm
t/mojo/daemon.t
t/mojo/lib/myapp-module-true.pl

Use `do` rather than `require` to load a mojo application to fix compatibility with new `module_true` core feature.
The return value of `require` is usually not a reasonable thing to rely on, aside from it being true. The first time requiring a file, it will return the value of the last statement in the file. The second time requiring a file, it will return a simple true value.
Mojo was bypassing this problem by deleting the `%INC` entry for the file, forcing it to always be loaded again. But the new `module_true` core feature will cause `require` to always return a simple true value rather than the last statement in the file. This does not apply to `do` though.
#2094

use do rather than require to load a mojo application

---

lib/Mojo/Server.pm
t/mojo/daemon.t

When switching from loading an application from using require to using do, the error was still trying to be captured after a surrounding eval. This error would always be empty, because the error from the do was not rethrown. It would still result in an undef application, so an error would be thrown, but it would not include the actual compile error.
Change the do call inside the eval to throw an error if no application is returned. The error is then recaught outside the eval. Also add a test that shows that the real compilation error is included in the output.
Fixes #2110

fix error reporting when loading applications with compile errors

---

lib/Mojo/Headers.pm

This improves readability by making it easier to find the methods that aren't
simply shortcuts to particular headers.
I have confirmed that the headers listed in %NAMES exactly matches those in
the pod, except for referer and referrer which have custom subs.

separate header shortcuts from other accessors

---

lib/Mojolicious/Controller.pm
t/mojolicious/static_prefix_lite_app.t

There is currently a bug where:
```
%= image('https://www.somesite.com/image.png')
```
produces
```
```
This PR adds an absolute check to the `file_path` and `asset_path` methods that currently breaks this.
This is breaking multiple of my systems in production. (And it seems its breaking others as well)
#2107

Add absolute check to url_for_asset and url_for_file to fix appending "/" to absolute file paths

---

lib/Mojo/Server/Morbo/Backend/Poll.pm
t/mojo/morbo.t

Updates Mojo::Server::Morbo::Backend::Poll to detect deleted files.
Currently Mojo::Server::Morbo::Backend::Poll does not restart when files are deleted.
No references currently

Triggers modified_files on file deletion

---

t/mojolicious/static_prefix_lite_app.t

Adds a test to ensure #2107 is working just fine in the proposed case.
Because this behavior working fine appears untested. 
None

Adding a test to ensure absolute paths get unmangled in the image helper.

---

lib/Mojolicious/Guides/Cookbook.pod

The example with GET makes no sense, as GET method has no body. Use POST instead.
When looking for the way how to do chunked requests I have searched the docs for POST, because I expected that should there be a relevant example, it would use POST. But the Cookbook uses GET for streaming body, which makes no sense.
Discussed on IRC #mojo.

Cookbook: POST instead of GET in streaming example

---

lib/Mojo/Base.pm
lib/Mojo/BaseUtil.pm
lib/Mojo/Util.pm
t/mojo/base_util.t
t/pod_coverage.t

Commit 7e9a2ad introduced a "require Mojo::Util" causing a significant chain of further dependencies being pulled in which IMHO should be avoided for the very base module which is in particular being advertised as useful for just enabling static code checks and common import checks.
This commit moves out the function "monkey_patch" into its own module to break or prevent the circular dependency between Mojo::Base and Mojo::Util.
With that the import of Mojo::Base is more efficient, `time perl -e 'use Mojo::Base`
on my system reduced from 224±12.08 ms to 52.0±2.3 ms which I consider a considerable improvement for Mojo::Base which is used as a baseclass in many cases.

Improve include time of Mojo::Base by extracting monkey_patch

---

lib/Mojo/JSON.pm
t/mojo/json.t

Encode perl's built in boolean values on perl 5.36 and newer
Newer perl versions can track if a value is a boolean rather than just a string or number. Since we can identify them as being booleans, they can be encoded in JSON as booleans. This also matches the behavior of newer versions of JSON::PP and Cpanel::JSON::XS
Fixes #2191

Mojo::JSON: encode core boolean values as json bools

---

lib/Mojo/Loader.pm
t/mojo/base.t
t/mojo/loader.t

The first commit removes use of the ' package separator in tests, to resolve #2085 (which is now an error in the latest Perl development releases which will remove that feature).
The second commit deprecates calls to Mojo::Loader::load_class that contain a ' package separator.
The feature will be removed in upcoming versions of Perl.
#2085, https://github.com/Perl/perl5/issues/22504

Deprecate accepting old apostrophe package separator in Mojo::Loader

---

.github/workflows/linux.yml
lib/Mojo/Util.pm
lib/Mojolicious.pm
lib/Mojolicious/Command/Author/generate/app.pm
lib/Mojolicious/Command/version.pm
lib/Mojolicious/Controller.pm
lib/Mojolicious/Guides/FAQ.pod
lib/Mojolicious/Guides/Growing.pod
lib/Mojolicious/Sessions.pm
t/mojo/util.t
t/mojolicious/lite_app.t
t/mojolicious/session_lite_app.t

SUSE Hack Week has started, so this is my first proposal for sessions with encrypted cookies. I've tried to stay as close to the mojo.js implementation as possible. To address #2200 i've also added a `Mojo::Util::generate_secret` function.
The feature is only available if [CryptX](https://metacpan.org/pod/CryptX) is installed, and needs to be enabled with `$app->sessions->encrypted(1)`.

Add support for encrypted sessions with CryptX

---

lib/Mojolicious/Guides.pod

Add a bit of documentation to the main guides CONVENTIONS section explaining the common example of a method that returns its invocant for chaining.
This construct is used a lot in doc examples, but doesn't represent how the method should actually be called and its intent may not be obvious.

Mojolicious::Guides: explain the convention of method examples that return the invocant

---

t/mojolicious/log_lite_app.t

Convert t/mojolicious/log_lite_app.t to use subtests
This is part of the ongoing effort to address #1520.
Converting this file to use subtests improves test isolation and readability.
https://github.com/mojolicious/mojo/issues/1520

convert t/mojolicious/log_lite_app.t to use subtests

---

lib/Mojo/Util.pm

Alphabetise function order within POD, currently 'network_contains' is showing between 'punycode_decode' and 'punycode_encode'.
Purely cosmetic, discovered when reading the page on metacpan this morning. Reorder for consistency.
Output of `perldoc Mojo::Util`, function list on the left of https://docs.mojolicious.org/Mojo/Util

Update Util.pm - Docuemntation - Alphabetise function order within POD

---

lib/Mojo/Message/Request.pm
t/mojo/request.t

RFC9112 §3.2-5 says that Host is mandatory, but can be an empty value.
resolves issue #2232.

fix_headers() now initializes Host header when needed

---

lib/Mojo/Parameters.pm
t/mojo/parameters.t

Treats `$query->parse(undef)` the same as `$query->parse('')`
This allows for $uri->query(undef) to properly clear the query string, which previously did not happen if the parameters object had already been parsed into `pairs`.
This usage might be seen with `$uri->query(undef)->fragment(undef)` to strip off all trailing components after the path.

support setting query parameters to undef

---

Changes
README.md
examples/responses.pl
lib/Mojo/Content.pm
lib/Mojo/SSE.pm
lib/Mojo/UserAgent/Transactor.pm
lib/Mojolicious/Controller.pm
lib/Mojolicious/Guides/Cookbook.pod
lib/Mojolicious/Types.pm
lib/Test/Mojo.pm
t/mojo/sse.t
t/mojolicious/sse_lite_app.t
t/mojolicious/types.t
t/test/mojo.t

I want to build a `Mojo::MCP` module implementing the [Model Context Protocol](https://modelcontextprotocol.io/introduction). It uses SSE as part of the transport layer, so it's time for Mojolicious to get support.

Add support for Server-Sent Events

---

lib/Mojolicious/Guides/Rendering.pod

Remove the paragraph stating that the status code of a `reply->exception` can be changed. Amend the "Also" at the beginning of the next paragraph.
Bashed my head too many times trying to understand why `$self->reply->exception->rendered(400)` was returning an HTTP 500 status code. It isn't possible.
IRC chat.
```
16:56 < Lucas_> question: https://docs.mojolicious.org/Mojolicious/Guides/Rendering#Rendering-exception-and-not_found-pages says that I can change the status code of an 
exception with ->rendered, but that isn't working. Tried both Mojolicious 9.37 and 9.39
16:56 < Lucas_> there is also an issue, https://github.com/mojolicious/mojo/issues/1014 , which says it won't be supported
16:57 < Lucas_> so, which one is it?
17:26 < kraih> The docs are wrong
```

Changing the status code of an exception isn't possible

---

lib/Mojo/Promise.pm

Change implementation of Mojo::Promise::AWAIT_ON_READY() to fix leak.
The original implementation used _finally(), which created multiple intermediate promise objects. These weren't settled until the event loop stopped, creating a memory leak and significant delay on stop. The simplified code directly registers callbacks without intermediate Promises, eliminating the leak while maintaining correct functionality.  This will also be quicker.
Memory::Usage before fix.
```
time    vsz (  diff)    rss (  diff) shared (  diff)   code (  diff)   data (  diff)
0  36420 ( 36420)  28800 ( 28800)   7168 (  7168)   1548 (  1548)  21796 ( 21796) START
1  45032 (  8612)  37376 (  8576)   7168 (     0)   1548 (     0)  30408 (  8612) counter=1000
3  53952 (  8920)  45952 (  8576)   7168 (     0)   1548 …
```

Fix memory leak in AWAIT_ON_READY

---

lib/Mojo/JSON.pm
lib/Mojolicious/Command/version.pm
t/mojo/json.t
t/mojo/json_xs.t

This matches the `convert_blessed`/`allow_blessed` behaviour of `Cpanel::JSON::XS` (since version 4.20, so also bump the requirement to that).

JSON-encode objects with no TO_JSON or stringification overload as null
