mojolicious/mojo

- Changes
s/fine_is_binary/file_is_binary/
> Fix minor typo in Change

- lib/Mojolicious/Renderer.pm
Sorry to bother you with a commit for something so simple!  But I know you like to keep your project / docs perfect!  :D
> use only one space character

- lib/Mojolicious/Plugin/PODRenderer.pm
Per http://irclog.perlgeek.de/mojo/2015-11-03#i_11475843
> $anchor variable is no longer needed

- lib/Mojo/Base.pm
Clarify that tap here means not "wiretap; eavesdrop; infiltrate" but "insert" and that "K Combinator" is a term in the relatively new Combinatory logic. Explain exactly what is going on for those new to these principles.
> Clarify K combinator

- lib/Mojolicious/Validator/Validation.pm
This seems to be a copy-paste error.
> Minor typo in Validation doc

- lib/Mojo/ByteStream.pm
- lib/Mojo/Util.pm
- t/mojo/bytestream.t
- t/mojo/util.t
A function to generate a URL-appropriate slug from an arbitrary string like a title.
This functionality is commonly used in web applications.
Implementation and tests based on slugify from django utils: https://docs.djangoproject.com/en/1.11/ref/utils/#django.utils.text.slugify
> slugify util function

- lib/Mojo/IOLoop/Client.pm
Currently, anything loading Mojo::IOLoop will automatically spawn a Net::DNS::Native thread pool (if it's installed, and $ENV{MOJO_NO_NNR} isn't set). With this change, the thread pool is only spawned once something calls ->connect on a Mojo::IOLoop::Client object, where Net::DNS::Native is used.
Example: `perl -MMojo::IOLoop -E'sleep 5' & sleep 2 && pgrep -aw perl`
It seems unnecessary to spawn thread pools for processes that will never need them, like many Mojolicious applications that only serve content.
> Only spawn Net::DNS::Native threads if Mojo::IOLoop::Client is used

- lib/Mojolicious/Command/get.pm
It can be hard to specify modern passwords generated by password managers into the url format given the restrictions on characters. It is much easier to do so only concerning bash escaping rather than worrying about url escaping too. To this end, this PR implements a -u flag (much like) what cURL provides.
> add cURL-style -u for username/password entry to the get command

- lib/Mojolicious/Plugin/Config.pm
- t/mojolicious/external/lib/MyApp.pm
- t/mojolicious/external_app.t
> set config stash value when config_override is used

- lib/Mojo/UserAgent.pm
Clean up Mojo::UserAgent code that handles proxy CONNECT requests.
Remove obsolete bits of code and make things look nicer.
IRC discussion
> Clean up code for CONNECT request handling

- lib/Mojo/DynamicMethods.pm
- lib/Mojolicious.pm
- lib/Mojolicious/Controller.pm
- lib/Mojolicious/Renderer.pm
- lib/Mojolicious/Routes.pm
- lib/Mojolicious/Routes/Route.pm
- lib/Mojolicious/Validator.pm
- lib/Mojolicious/Validator/Validation.pm
- t/mojo/dynamic_methods.t
I created a thing called Mojo::DynamicMethods and use it to kill AUTOLOAD
sri nerd sniped me by telling me to kill AUTOLOAD
I hate you all
> Review request - attempt at Mojo::DynamicMethods

- lib/Mojo/Content/MultiPart.pm
Spelling fix.
Spelling fix.
None.
> Fix spelling

- lib/Mojo/Util.pm
- t/mojo/util.t
Proposed for implementation of #1343. Calling for a vote from @mojolicious/core.
> Getopt return

- lib/Mojolicious.pm
Typo fix, going to merge this instantly.
> Fixed name even if funnier with a

- lib/Mojo/Message/Response.pm
- t/mojo/file.t
- t/mojo/json.t
- t/mojo/response.t
- t/mojo/transactor.t
Fixes various typing errors found, mostly in comments but also one in the string of a message response code
> Fix various typing errors

- README.md
Add a list of benefits you gain from using the Mojolicious framework.
Benefits have more promotional value than features
> Add high level benefits to the README

- lib/Mojolicious/Validator.pm
- t/mojolicious/validation_lite_app.t
Negative integers are numbers too.
Fix the code to match the documentation and clarify.
* #1375
> Validate negative integers

- lib/Mojo/DOM/CSS.pm
- lib/Mojo/IOLoop/Server.pm
- lib/Mojo/Util.pm
Transliteration is 10x faster and often more expressive
Of course changes are not necessary, but having faster operator inside nested loops is not a bad idea? :)
Good luck!
> Substitution replaced with transliteration

- lib/Mojo/UserAgent/Server.pm
This proposes a possible documentation correction.
I'm not for certain that this proposed change is correct, but it seems out of place with almost all other documentation, and it doesn't mirror the synopsis.
None.
> Fix documentation

- lib/Mojo/HelloWorld.pm
- lib/Mojo/IOLoop.pm
- lib/Mojo/JSON.pm
- lib/Mojo/Transaction.pm
- lib/Mojo/Transaction/HTTP.pm
- lib/Mojo/Transaction/WebSocket.pm
- lib/Mojolicious/Command.pm
- lib/Mojolicious/Command/Author/cpanify.pm
- lib/Mojolicious/Command/Author/generate.pm
- lib/Mojolicious/Command/Author/generate/app.pm
- lib/Mojolicious/Command/Author/generate/lite_app.pm
- lib/Mojolicious/Command/Author/generate/makefile.pm
- lib/Mojolicious/Command/Author/generate/plugin.pm
- lib/Mojolicious/Command/Author/inflate.pm
- lib/Mojolicious/Command/cgi.pm
- lib/Mojolicious/Command/daemon.pm
- lib/Mojolicious/Command/eval.pm
- lib/Mojolicious/Command/get.pm
- lib/Mojolicious/Command/prefork.pm
- lib/Mojolicious/Command/psgi.pm
- lib/Mojolicious/Command/routes.pm
- lib/Mojolicious/Command/version.pm
- lib/Mojolicious/Routes/Route.pm
- lib/Test/Mojo.pm
This fixes the grammatical errors recently introduced into the documentation.
ether mentioned this in IRC.
> Fix recently introduced grammatical errors

- lib/Mojo/Promise.pm
Does pretty much what it says on the tin.
start_next now returns () so it can be used directly in ->then for the initially started promises
__SUB__ means I don't have to have start_next close over itself so I can kill the finally
@items = () in the reject for the non-initial promises makes start_next into a no-op from then on and also returns ()
> use __SUB__ to simplify Mojo::Promise->map code

- t/mojo/dom.t
I converted the tests for Mojo::DOM to using subtests.
I saw on IRC that we're planning on converting all tests to using subtests, and I wanted to give back a little (you guys literally make my livelihood).
This addresses issue #1520. I hope to be able to do more in the future, too.
> converted Mojo::DOM tests to using subtests

- lib/Mojo/DOM.pm
Make documentation more friendly for developers not familiar with namespaces (like me)
I was confused on what method should return. A simple example should help eliminate confusion.
Issue #1548
> provide example of a result for the namespace method

- t/mojo/bytestream.t
- t/mojo/collection.t
- t/mojo/content.t
- t/mojo/cookie.t
- t/mojo/cookiejar.t
More mojo tests converted to use subtests.
> Convert more t/mojo/ tests to use subtests

- lib/Mojolicious/Guides/Cookbook.pod
This adds a simple reverse proxy example using Envoy.
Fixes #1543.
> Add Envoy Proxy configuration example

- t/mojo/signatures.t
Convert t/mojo/signatures.t to use subtests.
Issue #1520
> Convert t/mojo/signatures.t to use subtests

- .github/workflows/linux.yml
Test on Perl 5.32 also? :sweat_smile:
Perl 5.32 is latest stable, so it's probably good to test there too. :smile:
Closes #1574
(As always, happy to rebase, amend, close, etc. :+1: :heart:)
> Also run GitHub Actions tests on Perl 5.32

- t/mojo/parameters.t
Tests for `Mojo::Parameters` in `t/mojo/parameters.t` converted to use subtests.
Continuing ongoing effort
#1520
> Convert parameters.t to subtests

- t/mojo/path.t
Tests for `Mojo::Path` in `t/mojo/path.t` converted to use subtests.
Continue ongoing effort.
#1520
> Convert path.t to subtests

- t/mojo/log.t
Subtests for Mojo::Log
as discussed in #1520
> Mojo::Log tests now use subtests

- t/test/mojo.t
Added Test::Mojo::header_* tests.  Though now I'm unsure of the merge-ability of the separate pull requests, even though it seemed like a good idea to separate the concerns a bit at first.
More tests addressing #1488 
#1488
> Added Test::Mojo::header_* tests

- t/test/mojo.t
Added Test::Mojo::content_* tests.  If it seems like I'm on the right path here, I can continue adding tests for more methods.
Part of addressing #1488 
#1488
> Added tests for Test::Mojo::content_* methods

- t/test/mojo.t
Added Test::Mojo::attr_* tests
Requested changes in #1488 
#1488
> Added Test::Mojo::attr_* tests

- lib/Mojo/Server/Prefork.pm
- lib/Mojolicious/Guides/Contributing.pod
> fix 2 links in mojo docs

- Makefile.PL
- lib/Mojolicious/Guides.pod
- lib/Mojolicious/Guides/Contributing.pod
- lib/Mojolicious/Guides/Cookbook.pod
- lib/Mojolicious/Guides/FAQ.pod
- lib/Mojolicious/Guides/Growing.pod
- lib/Mojolicious/Guides/Rendering.pod
- lib/Mojolicious/Guides/Routing.pod
- lib/Mojolicious/Guides/Testing.pod
- lib/Mojolicious/Guides/Tutorial.pod
see https://freenode.net/kb/answer/chat
> update freenode references to preferred host

- t/mojo/transactor.t
t/mojo/transactor.t
Ongoing initiative. Wanting to contribute.
#1520
> Convert t/mojo/transactor.t to use subtests

- t/mojolicious/ojo.t
Subtests for ojo
as discussed in #1520
Want to contribute :)
> convert t/mojolicious/ojo.t to use subtests

- t/mojolicious/multipath_lite_app.t
Convert t/mojolicious/multipath_lite_app.t to use subtests
I want to contribute to the cause :) 
#1520
> convert multipath_lite_app.t to use subtests

- t/mojolicious/validation_lite_app.t
convert t/mojolicious/validation_lite_app.t to use subtests
I want to contribute to converting all tests to use subtests
Discussion in #1520
> convert t/mojolicious/validation_lite_app.t to use subtests

- t/mojo/tls.t
Split out from #1669 to help reviewers.
Migration to subtests.
#1520
> convert tls.t to subtests

- t/mojolicious/external_app.t
convert `t/mojolicious/external_app.t` to use subtests
#1520
> convert t/mojolicious/external_app.t to use subtests

- t/mojolicious/upload_stream_lite_app.t
convert `t/mojolicious/upload_stream_lite_app.t` to use subtests
wanting to contribute to the subtest conversion
Discussed in #1520
> convert t/mojolicious/upload_stream_lite_app.t to use subtests

- t/mojolicious/embedded_app.t
convert `t/mojolicious/embedded_app.t` to use subtests
want to contribute to the subtest mission
> convert t/mojolicious/embedded_app.t to use subtests

- lib/Mojolicious/Guides/FAQ.pod
Capitalize "I" in the FAQ question
> Minor typo

- t/mojolicious/restful_lite_app.t
convert `t/mojolicious/restful_lite_app.t` to use subtests
> convert t/mojolicious/restful_lite_app.t to use subtests

- t/mojolicious/proxy_app.t
convert `t/mojolicious/proxy_app.t` to use subtests
> convert t/mojolicious/proxy_app.t to use subtests

- t/mojolicious/json_config_mode_lite_app.t
convert `t/mojolicious/json_config_mode_lite_app.t` to use subtests
contributing to the subtest conversion
#1520
> convert t/mojolicious/json_config_mode_lite_app.t to use subtests

- t/mojolicious/dispatcher_lite_app.t
convert `t/mojolicious/dispatcher_lite_app.t` to use subtests
i want to contribute to using subtests throughout.
> convert t/mojolicious/dispatcher_lite_app.t to use subtests

- t/mojolicious/signatures_lite_app.t
convert `t/mojolicious/signatures_lite_app.t` to use subtests
> convert t/mojolicious/signatures_lite_app.t to use subtests

- t/mojolicious/upload_lite_app.t
convert `t/mojolicious/upload_lite_app.t` to use subtests
> convert t/mojolicious/upload_lite_app.t to use subtests

- t/mojolicious/static_lite_app.t
convert `t/mojolicious/static_lite_app.t` to use subtests
I want to contribute
Discussion: #1520
> convert t/mojolicious/static_lite_app.t to use subtests

- t/mojolicious/twinkle_lite_app.t
convert `t/mojolicious/twinkle_lite_app.t` to use subtests
wanting to contribute to the conversion to subtests
discussed in #1520
> convert t/mojolicious/twinkle_lite_app.t to use subtests

- t/mojo/response.t
- t/mojo/roles.t
- t/mojo/user_agent_socks.t
Convert three .t files to use subtest in response to issue #1520.  This replaces PR #1829.
> Convert to using subtests per issue #1520

- lib/Mojolicious/Guides/Growing.pod
Minor grammar corrections.
Caught during work on mojo.js guide, opening PR here first.
> Fix punctuation. Avoid using simply twice in the same paragraph.

- t/mojo/dynamic_methods.t
Tests in `t/mojo/dynamic_methods.t` converted to use subtests.
Help convert remaining subtests.
#1520
> Convert t/mojo/dynamic_methods.t to use subtests

- t/mojo/websocket.t
Tests in `t/mojo/websocket.t` converted to use subtests.
Help convert remaining subtests.
#1520
> Convert t/mojo/websocket.t to use subtests

- t/mojo/websocket_proxy.t
Tests in `t/mojo/websocket_proxy.t` converted to use subtests.
Help convert remaining subtests.
#1520
> Convert t/mojo/websocket_proxy.t to use subtests

- lib/Mojolicious/Command/Author/generate/app.pm
- lib/Mojolicious/Controller.pm
- lib/Mojolicious/Guides/Growing.pod
- lib/Mojolicious/Guides/Rendering.pod
- lib/Mojolicious/Plugin/TagHelpers.pm
- lib/Mojolicious/Static.pm
- t/mojolicious/commands.t
- t/mojolicious/public/assets/foo.ab1234cd5678ef.css
- t/mojolicious/public/assets/foo.ab1234cd5678ef.js
- t/mojolicious/public/assets/foo/bar.321.js
- t/mojolicious/public/assets/foo/bar/baz.123.js
- t/mojolicious/public/assets/foo/bar/baz.development.js
- t/mojolicious/public/assets/foo/bar/test.ab1234cd5678ef.min.js
- t/mojolicious/public/assets/foo/bar/yada.css
- t/mojolicious/static_lite_app.t
- t/mojolicious/tag_helper_lite_app.t
This PR adds the long discussed support for static assets generated by bundlers like Webpack. See the included documentation for details.
> Add support for static assets

- .github/workflows/linux.yml
- .github/workflows/macos.yml
- .github/workflows/windows.yml
GitHub should now show annotations for errors in PRs.
> GitHub annotations

- t/test/mojo.t
Adding tests for the Test::Mojo::message_* methods.
Issue #1488.
#1488
> Adding Test::Mojo::message_* tests.

- Changes
Very minor typo. No big whoop.
> typo in Changes
